### PR TITLE
Balance T2 cruiser

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
As I've said before I dislike the removal of minor energy created by units, it make a massive difference to game play

**Comment by skymyj** [comment]
Wich unit ?

**Comment by skymyj** [comment]
Added energymake and use and storage on tll cruiser :X

**Comment by nixtux** [comment]
So what will happen if all units produce no energy, and someone destroyed all your eco, game over for you as any unit that needs energy to fire is total broken at this point

**Comment by skymyj** [comment]
well. If you have no energy resource, you dye on this game. It's not few units that will give you an other chance to take new start.
But i didn't change a lot of things here about energy

**Comment by nixtux** [comment]
On bug games maybe but small games no, I will merge this for now, but I'm going to check all old values and adjust back at some point

**Comment by skymyj** [comment]
A good thing could be to delete all energyuse or fix at 0 for all battle units and cons.
Only radar, jammer and special units will have x energyuse. Will be more sense imho.

All t1 produce +1 and +10 for cons
All t2 produce +3 and +200 for cons (3k cost m)
all t2.5 produce +5
All t3 unit produce 10 and t3.5 +20

**Comment by skymyj** [comment]
Its why i deleted all energy 2 years ago

**Comment by nixtux** [comment]
I know, I was not happy with it then and still not.

**Pull request merged**
