### PR TITLE
tllcoyote - revert to old balance, add paralyzemultiplier

### PR DESCRIPTION
**Pull request by ksilversurfer**
Add paralyzemultiplier to match scale of emp damage of panther

### CODE REVIEW

**Comment by skymyj** [comment]
So if i understand, add multiplicator for all aa units (secondary weapon). Razorback is not as good as kargareth.

**Comment by skymyj** [comment]
Tllcoyote stats are less than reapzr or bulldog. Cause of this aa. 
You can't add paralysecoeff for some units without description uniti line

**Comment by ksilversurfer** [comment]
hmm, so we stay with AA nerf then
again tllcoyote cant have strong AA, that make him op
Maybe you can suggest some balance for it?

**Comment by skymyj** [comment]
Don't know. Maybe decrease aa. 75dmg vs 100 atm.

**Comment by ksilversurfer** [comment]
it will be still too much

**Comment by ksilversurfer** [comment]
i vote to set to 33dmg/s of AA weapon

**Comment by skymyj** [comment]
We should see hp drone. Goal is to shoot 2 times to kill one. If you decrease dmg change reload instead damage missile.

**Comment by skymyj** [comment]
If drone hp is 100hp up

**Comment by ksilversurfer** [comment]
bladew maxdamage = 60,
so with 40dmg with reaload of 2sec  will be 2 shots to kill it

**Comment by ksilversurfer** [comment]
other idea leave 100dmg, but set reload time to 2.75sec to test

**Pull request closed without merging**
