### PR TITLE
Add-energy-for-some-units

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
You not adding energy, having energyuse = energymake is pointless stop it please. Also have storage =0 is pointless as it defaults to zero,  another pointless addition that needs to stop.

**Comment by skymyj** [comment]
Well, I'm just thinking that you had a function codage, that will delete all energyuse for each unit or someting like this.

**Comment by ksilversurfer** [comment]
skymyj is you set energymake same as energyuse then result is 0
same as -1 + 1 
i mean that it not give anything, its exactly the same as energymake = 0
and btw. armraz and corkarg weapons not use energy for shot.

Maybe you want to refet to OTA ? (iirc some units had +5e and -5 e)

**Comment by skymyj** [comment]
Others options could be :
- to delete all energyuse if unit has a weapon
- energyuse = 0 if unit not moving or not shooting

**Comment by ksilversurfer** [comment]
ah if not moving - then it make sense

**Comment by skymyj** [comment]
Some units are totally op with energy make like invisible kbot arm (they produce +30 E / S)
I think Nix is able to delete all energyuse.

**Comment by ksilversurfer** [comment]
I think this pr should be closed.

**Comment by ksilversurfer** [comment]
reference: Energy Make and Storage for all units with energy weapons. #248

**Pull request closed without merging**
