### PR TITLE
Add helepolis unit

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Add Helepolis for Commander Battle and Air Builder.
Goal is to have T2.5 for TLL Kbot like Krotaar and vengence.
Tested and it works.

**Comment by ksilversurfer** [comment]
if tested and it works, i agree

**Comment by nixtux** [comment]
Imo helepolis looks too much like sumo and that why it was never added, even worse you added it to tll, when  it looks like sumo which is core

**Comment by skymyj** [comment]
So Nix, I have an other proposition : Is it possible to add for Core : just for morphing. 
could be the last morph tree for Sumo ?

**Comment by skymyj** [comment]
This unit is really awesome, and looks so nice.

**Comment by skymyj** [comment]
I remember about a Fido for ARM with HLT. 
Could be nice to add just for fido morph too.

**Comment by skymyj** [comment]
Added Morph Tree Helepolis.
Could change Icon this evening.

**Comment by skymyj** [comment]
Done and tested

**Comment by ksilversurfer** [comment]
i cant merge if nixtux not agree

**Pull request merged**
