### PR TITLE
Balance Cavalier

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by pcdummy** [comment]
total : 230dmg/s => 130dmg/s of second weapon.

and 200 points hp decrease.

Got overrunned by 10 or 20 of these, i love that nerf

**Comment by ksilversurfer** [comment]
I not understand why you want nerf Cavalier, its already not very usefull unit. 
Spiders are better.
I vote b

**Comment by nixtux** [comment]
110 dps to 65, that's not a nerf that's crippling the unit, a big fat no from me

**Comment by pcdummy** [comment]
@nixtux Its second weapon?

**Comment by skymyj** [comment]
Actually, this unit is good balanced except the second weapon with too much damage. 
I want to have a second weapon with same stats than zeus.
So if we decrease the weapon, we can also too decrease the cost. 
His strengh anyways is this main weapon at 750 range.

**Comment by ksilversurfer** [comment]
vote NO

**Pull request closed without merging**
