### PR TITLE
Update description of T4 Razorback

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by Antarac** [comment]
Unit seems to be the counterpart of the Core Karganeth that is all terrain on t3 and t4.
Would be logical that Razorback is also all terrain in t3 and t4.
If the big t4 Razorback is able to go all terrain it would be technically even more easy that a smaller t3 version goes all terrain cause lesser weight.

**Comment by skymyj** [comment]
I think, we have to not change description but movement class. 
There is already T4 Raptor unit with All-terrain.

**Comment by skymyj** [comment]
Movement class to remplace by HKBOT4

**Comment by nixtux** [comment]
Y for description, but no for movement class it needs to match unit footprint

**Comment by skymyj** [comment]
Well. I thought that's a bug. But it's not...
This unit has always been all-terrain ? No sense. Why razor v0 is not and why v1 is ???

**Comment by ksilversurfer** [comment]
skymyj are you ok mate?

**Comment by skymyj** [comment]
Well, it's my fault. I thought you are talking about raptor. (razorback with missile). 
And I think, we awere agree to delete all terrain feature for razorback. 

what do you think Silver ?

**Comment by skymyj** [comment]
I think, i not good communicate. I have to increase my skills in english :)

**Pull request closed without merging**
