### PR TITLE
Balance New T3 Cons and T4 Lab

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Balance All Cons and Lab.
Miss TllLab

**Comment by nixtux** [comment]
tllprototype

**Comment by nixtux** [comment]
im up for making a lab for valiant, like arm/core labs

**Comment by skymyj** [comment]
Ok. Done for these units. 
I don't know for tlldoc if it's good unit on panel menu.

Is the tllprototype will be built by T2 cons ?

**Comment by skymyj** [comment]
and t3 air cons ? made by wich unit ?

**Comment by nixtux** [comment]
tllbuilderlvl3>tllprototype

**Pull request merged**
