### PR TITLE
Wreckage and Debris

### PR DESCRIPTION
**Pull request by Antarac**
A little Collection.

### CODE REVIEW

**Comment by Antarac** [comment]
Barret got 3 types of wreckage/metal shards/debris.
Is the change ok that way?

**Comment by nixtux** [comment]
Dont worry about featuredefs there autogenerated at game start, i will try and bake then into the unitdefs

**Comment by Antarac** [comment]
Hehe, i wondered already why i dont see so many ingame.
Ok, i just stop with it.

**Comment by nixtux** [comment]
Ah what you did was good, you reminded me to clean up all values, currently doing it now, there is also many deprecated tags that will go also.

**Comment by Antarac** [comment]
Allright, cool =)

**Comment by nixtux** [comment]
ive mass updated wreck/debris decsription here https://github.com/techannihilation/TA/commit/ce6d750b3d3d0669f3a4c1a8074031584a8775e4

**Comment by nixtux** [comment]
there are some errors now ie description = "BROADSIDE Wreckage"
as it uses unitdef  name

**Comment by nixtux** [comment]
Closing issue, as all description are now baked

**Pull request closed without merging**
