### PR TITLE
Morph V2

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Deleted the non sense morph like flash => lighting and laser => flamer

**Comment by nixtux** [comment]
yep corak1 > corpyro makes no sense at all

**Comment by Antarac** [comment]
I would understand if you say corak1 is to strong,
cause of "zerg rush", since i killed many people with it.

It's cool that you get rewarded if you take care of the AK's.
To me it's the only useful robot from core t1 kbot factory.

**Comment by skymyj** [comment]
I would understand if you say corak1 is to strong, => yeah strong but not the discussion here.
Ok for your comment

**Pull request merged**
