### PR TITLE
Balance energy cost and explosion after selfD

### PR DESCRIPTION
**Pull request by skymyj**
If you seldF this tactical, all at 1000 range diseapear

### CODE REVIEW

**Comment by nixtux** [comment]
Why a reduction of sight distance for a t2 units seems as random change

**Comment by nixtux** [comment]
Sorry didn't understand description also? What bug is this trying to fix?

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA/blob/master/units/tllsilo.lua
=> if you compare to icbm, less sight. Structure didn't need long range. 
But whatever, i can change if you dislike it. 

Important point here is the energy cost : too low.
If you selfd, same effect than icbm structure. It's op.

**Comment by ksilversurfer** [comment]
moho geos should be not safe from definition.
I not agree to nerf moho geo explosion

**Comment by ksilversurfer** [comment]
agree to nerf tactical self d explosion

**Comment by nixtux** [comment]
Make new pr with updated changes

**Comment by ksilversurfer** [comment]
just compared to armemp, we can increase energy cost but **not 2x**
armemp 1601m, 28978e, build 79247                -> E/M cost = 1601m + 0.016 * 28978e = 2064m
cortron 1920m, 13938e, build 58927                  -> E/M cost = 1920m + 0.016 * 13938e = 2143m

armemp range 4500, dmg 20sec emp at 96000dmg
cortron range 2750, dmg 2500

so i can agree to increase energy cost by 25%-35%, otherwise will be too expensive

**Comment by ksilversurfer** [comment]
or not better to increase metal cost instead?

**Comment by ksilversurfer** [comment]
> https://github.com/techannihilation/TA/blob/master/units/tllsilo.lua
> => if you compare to icbm, less sight. Structure didn't need long sight.
> But whatever, i can change if you dislike it.
> 
> Important point here is the energy cost : too low.
> If you selfd, same effect than icbm structure. It's op.

Why comparing to nukes???
tactical weapons are a different story

**Comment by skymyj** [comment]
#345

**Pull request closed without merging**
