### PR TITLE
Add obliterator1

### PR DESCRIPTION
**Pull request by skymyj**
Tested and work

### CODE REVIEW

**Comment by ksilversurfer** [comment]
dont add another cob script if old script is the same!
Just add new line in tllobliterator1.lua
script = "tllobliterator.cob",

**Comment by skymyj** [comment]
Done.  I had issue. So I deleted it. And didn't add line script then.
Now it's ok.

**Comment by nixtux** [comment]
First how much is this scaled by? 
Wreak footprints, mass, losemitheight, yardmap, are all same as original unit there could be more I only quickly checkes
Yardmap errors to infolog ergo you didn't test correctly 
I bet AO plates don't line up correctly now

**Comment by skymyj** [comment]
Scale by 2.035. 
What is ao plates?

**Comment by skymyj** [comment]
For infolog, I use a $test version from few weeks. So I couldn't anticipate this bug. Sorry

**Comment by nixtux** [comment]
Did you test scripts works, as if it contains move commands they need scaling also (bet you didn't test)

**Comment by skymyj** [comment]
You won. You're right. I did'tn thest them. 
Now I know that I have to slow down movement.

**Comment by nixtux** [comment]
No not slow down movement just multiple movement lengths by the same factor you scaled unit.  Only effects move in cob/bos script

**Comment by skymyj** [comment]
Upsacling move scale in cob / bos files

**Comment by ksilversurfer** [comment]
tested all?

**Comment by skymyj** [comment]
Yes

**Comment by nixtux** [comment]
It's not finished imo

**Comment by nixtux** [comment]
Please fix your shit before making more PR

**Comment by skymyj** [comment]
capture

Ok to havI will recheck this. 
Whatever, there are bugs with your new model Nix. You increase Y size, but now, gun penetrate body.

**Comment by skymyj** [comment]
Sorry for this mistake.
Just fixed and tested. 
It's work now.

**Comment by nixtux** [comment]
Mass is same as original unit
Los/radar emit height need scaling
Did you fix scale in script (move)?

**Comment by nixtux** [comment]
Yardmap need adjusting now due to footprint change

**Comment by skymyj** [comment]
Yes, i adjusting scale

**Comment by skymyj** [comment]
Done.

**Comment by nixtux** [comment]
Not done

**Comment by nixtux** [comment]
Not done,  diff with base and you will see why

**Comment by skymyj** [comment]
Added for T3 builder.

**Comment by skymyj** [comment]
Adjusted yardmap

**Comment by nixtux** [comment]
Radaremitheight and losemitheight need scaling by the same factor you enlarged the unit

**Comment by skymyj** [comment]
Done

**Pull request merged**
