### PR TITLE
VERSION{v3.08.0}

### PR DESCRIPTION
**Pull request by ksilversurfer**
Need add missing icons before release and fix mines

### CODE REVIEW

**Comment by ksilversurfer** [comment]
i will make list

**Comment by ksilversurfer** [comment]
{tllcenturion, tllleopard, tllmcv, tllcrawler, cormkl}

**Comment by nixtux** [comment]
Ohh I wonder how long the list will be now xD

**Comment by skymyj** [comment]
Should be the v4.00.00

**Comment by ksilversurfer** [comment]
it will be pain now to update all xD

**Comment by ksilversurfer** [comment]
DELETE - BECOUSE MAKE NO SENSE NOW

```
[13:36:33] <[KING]Silver> IM VERY SORRY I NOT MADE CHANGELOG - IM SOOO BUSY  :(((((((((((((
[13:36:42] <[SRG]keijj0> yeah start it now
[13:36:49] <[SRG]keijj0> just put simple things there
[13:36:51] <[KING]Silver> can i delete old?
[13:36:54] <[SRG]keijj0> YES
[13:36:56] <[SRG]keijj0> just start now
[13:36:58] <[KING]Silver> and start from now?
[13:37:04] <[SRG]keijj0> yep
[13:37:10] <[KING]Silver> Coool TY mate
[13:37:14] <[SRG]keijj0> its much better to see whats up from there
[13:37:22] <[SRG]keijj0> that ppl dont have to find out when they do something
````

**Comment by pcdummy** [comment]
Please make a release v4.00.00 :)

**Pull request merged**
