### PR TITLE
Update tllawindtrap.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Can you remove the changes to arm/core for now please

**Comment by skymyj** [comment]
Done

**Comment by nixtux** [comment]
Nope buildtime is still there

**Comment by skymyj** [comment]
But it's commun change for all faction.

**Comment by nixtux** [comment]
It's a balance change so should be discussed as a separate issue first see https://github.com/techannihilation/TA/issues/294

**Comment by nixtux** [comment]
I will merge once changes to arm core adv wind has been removed

**Comment by skymyj** [comment]
done

**Pull request merged**
