### PR TITLE
Balance T1.5 Bertha

### PR DESCRIPTION
**Pull request by skymyj**
Energy cost for T2 Bertha : 62500. T1.5 = 120KE :X 
We have to decrease Energy cost vs T2 Bertha.

### CODE REVIEW

**Comment by skymyj** [comment]
Add morph tree between T1.5 and T2 bertha

**Comment by ksilversurfer** [comment]
agree but i vote to reduce build time too by 30%

**Comment by ksilversurfer** [comment]
and we need make t1.5 shields cheaper too !

**Comment by skymyj** [comment]
I deleted branch. So I can't change other lines. 
But we could change Time in other request. And balance with Shield T1.5 time, cost...

**Pull request merged**
