### PR TITLE
Fix some units added (textures missing)

### PR DESCRIPTION
**Pull request by skymyj**
image
=> add nice holes
Missing a texture for vhlt. 
Missing a texture for corfmd

### CODE REVIEW

**Comment by nixtux** [comment]
Can't open tllvhlt in upspring or 3do builder

**Comment by nixtux** [comment]
So what is currently wrong with tllvhlt can't see any issue ingame

**Comment by skymyj** [comment]
It's very hard to see it.
take the bottom camera. You will see it on base.

**Comment by nixtux** [comment]
Still not going to merge anything that cant be reopened, please remake seperate pr

**Pull request closed without merging**
