### PR TITLE
Balance medium tank for lucy

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
What's the reason for this change?

**Comment by skymyj** [comment]
We made some test with Lucy and MrWeak. 
If you take 6 tank Arm/Core Vs 5 TLL :  
- TLL wins Vs Arm at ~same cost
- TLL lost Vs Core at ~same cost
- CORE WinsVs Arm (but cost high too)

Sam test with 5 tank Core and 5 TLL. Core wins again.

We think, the Core have too much Range vs TLL (370vs 315) and have better speed. So, they are Op vs TLL Faction.

**Comment by nixtux** [comment]
I disagree with range for upgraded being the same as std units, I'm not saying the is no issue but can you address, while keeping range boost for upgraded units.

**Comment by skymyj** [comment]
Done

**Pull request merged**
