### PR TITLE
Nerf AK-X1

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by skymyj** [comment]
Big nerf. Is it possible to test together vs Krogtaar ?

**Comment by ksilversurfer** [comment]
yes ofc we can test, i think i nerfed too much HP.
Instead we can increase build time

**Comment by ksilversurfer** [comment]
should be fine imo

**Comment by skymyj** [comment]
I'm ok now. Just if you can keep range for blue laser. Cause : I want to harmonize with other laser blue at range 600. (juggernault). If you want change another feature.

**Comment by skymyj** [comment]
I thought too, at a many burst for primary weapon like heldriver. Could be more fun.
If you see weapon, look like at a machine-gun

**Comment by ksilversurfer** [comment]
yea :D

**Pull request merged**
