### PR TITLE
Add tll combat T1 engineerer

### PR DESCRIPTION
**Pull request by skymyj**
Balance tllbuilderlvl2 and add HLT

### CODE REVIEW

**Comment by skymyj** [comment]
Not finished yet

**Comment by skymyj** [comment]
To do : 
Add gatling.
Delete old stuff from tllcom 5 6 7

**Comment by nixtux** [comment]
Why remove upg Web?

**Comment by skymyj** [comment]
I did ? I think not :)

**Comment by skymyj** [comment]
Added HLT.

**Pull request merged**
