### PR TITLE
Make T3 Razorback All-Terrain

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by Antarac** [comment]
Unit seems to be the counterpart of the Core Karganeth that is all terrain on t3 and t4.
Would be logical that Razorback is also all terrain in t3 and t4.
If the big t4 Razorback is able to go all terrain it would be technically even more easy
that a smaller t3 version goes all terrain cause lesser weight.

**Comment by nixtux** [comment]
Yes from me

**Comment by skymyj** [comment]
WOW 

Guys, With all respect I have, I THINK you make all a big mistake with t3 and t4. 
If you compare these 2 units : 
1- We have a really strong unit (razorback). Compare HP and damage/S with cost... Too strong to be an all terrain
2-  So If I follow your logic, Catapult have to be All Terrain too cause Vanguard is too. I hope you see the no sense here.
3- For T4, there is Raptor unit, and it's balaned with T4 Karg.
4- BA is an other mode for sure, but stay good balanced. Please, don"t change that.

Thanks and it's just my opinion.

**Comment by skymyj** [comment]
corkarg : 
buildcostenergy = 92800,
buildcostmetal = 3800,
maxdamage = 9000,
maxvelocity = 1.5,
damage = 520 (with rocket and missile) + AA

armraz : 
buildcostenergy = 119000,
buildcostmetal = 3810,
maxdamage = 15800,
maxvelocity = 2.5,
dmg/s : 666

To resume, we have 2 units with same cost, but with better stats for Razorback. So, if you want add all-terrain, you have to decrease all the stats of zaorback T3 (and same way for T4)

**Comment by ksilversurfer** [comment]
skymyj is right Razorback can be actually OP is will be all-terrian.
It is much faster than corkarg (vel 2.5 vs 1.5) and it also has much more hp (15800 vs 9000)

**Pull request closed without merging**
