### PR TITLE
Add T3 Hover to test

### PR DESCRIPTION
**Pull request by skymyj**
https://1drv.ms/v/s!AgjKPxaKD1zLlhS31sp4U0v90ERA

### CODE REVIEW

**Comment by nixtux** [comment]
Hmm why lups for hover + too many effects

**Comment by skymyj** [comment]
It's beatiful. But i can delete it.
Add arm hover

**Comment by skymyj** [comment]
image
image
image

**Comment by ksilversurfer** [comment]
remove too many lups? or merge?

**Comment by skymyj** [comment]
Deleted lups

**Pull request merged**
