### PR TITLE
Heavy Metal!

### PR DESCRIPTION
**Pull request by Antarac**
"Heavy Fatboy - Very Heavy Plasma Kbot (heavy boost)"	Arm T2.5 Kbot

Thats really heavy ;)

Delete "heavy" from "(heavy boost)" since
i seen other unit with "(Boost)" only?

### CODE REVIEW

**Comment by skymyj** [comment]
I will delete all the "(xxx)"

**Comment by Antarac** [comment]
If you want i can start a pull request for it and add the first few units with (xxx).
I will close this pull request if (heavy hoost) gets deleted.

**Comment by skymyj** [comment]
When i write I will, it's : Id like.
Just change add a commit to this request

**Comment by Antarac** [comment]
Allright =)
I just dont know what you meant with
"Just change add a commit to this request"?

**Comment by skymyj** [comment]
Edit again this request :)

**Comment by skymyj** [comment]
And add the modification

**Comment by Antarac** [comment]
Deleted "(heavy boost)".

**Pull request merged**
