### PR TITLE
Balance Bombers Cost

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
The missing burstrate change needs to happen

**Comment by nixtux** [comment]
Sky have you finished with this change set?

**Comment by skymyj** [comment]
No. I have to check all other bombers ans test the strategic bombers burstrate

**Comment by skymyj** [comment]
Ok for me.
I decrese cost of Scout T2. Cause never used vs T1 scout.
Now, they will be more usefull than TA

**Pull request merged**
