### PR TITLE
Upsacle TSAR

### PR DESCRIPTION
**Pull request by skymyj**
#967

### CODE REVIEW

**Comment by ksilversurfer** [comment]
i vote no

**Comment by ksilversurfer** [comment]
you can increase size but not x2 - its tooo big !! xD

**Comment by skymyj** [comment]
I can decrease at 0.8 from these models. 
From original, it will be 1.6

**Comment by ksilversurfer** [comment]
ook

**Comment by skymyj** [comment]
Done. You can merge it

**Pull request merged**
