### PR TITLE
TSAR final weapon Keiij0 idea 10M

### PR DESCRIPTION
**Pull request by ksilversurfer**
Please vote/comment if you like this.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
- TSAR metal and energy cost **x7**
- One missile is loaded when TSAR is finished
- Range same as nuke

**Comment by skymyj** [comment]
Ok for cost.
I'm for delete the amunition.
I think at a shot that cost 1Million E and with 120s reload

**Comment by skymyj** [comment]
With less damage : 150K

**Comment by skymyj** [comment]
Always enough to kill all eco in 1 shot

**Comment by ksilversurfer** [comment]
im not sure with the cost yet, maybe 10million is too much..
i think 7-8million metal should be ok, but increase energy cost a bit.

**Pull request merged**
