### PR TITLE
1/4 Construction T3 

### PR DESCRIPTION
**Pull request by skymyj**
#507

### CODE REVIEW

**Comment by skymyj** [comment]
If you are agree, we should delete now the anti T3/T4 gun from T2 Cons. 
And delete the T3 Lock for these weapons

**Comment by nixtux** [comment]
Imo tlldoc should not build tllprototype, that should be built by tllbuilderlvl3 only

**Comment by skymyj** [comment]
I think, if we can lock the TLLcolossus, we should add tllprototype for T3 cons. Same than Arm /Core

**Comment by skymyj** [comment]
See #525

**Pull request merged**
