### PR TITLE
Add T4 MM for test

### PR DESCRIPTION
**Pull request by skymyj**
image

image

### CODE REVIEW

**Comment by nixtux** [comment]
Scripts are incomplete for MM can't merge pr

**Comment by nixtux** [comment]
And the top unit looks more like an energy storage, all MM have some visual on/off animation

**Comment by skymyj** [comment]
Yes, a Metal Maker miss 2 function. I will add them. 
For Core, there is an animation like T2/T3 MM.
For rm, I can activate/desactive the dome/circle.

**Comment by skymyj** [comment]
Added new script/model for Arm.
Now Arm MM has on/off animation

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
For Core model. we could add in decription : Metal maker / Storage. And Add like 100K Storage E

**Comment by nixtux** [comment]
Script still need work, much to remove (hint), what where the units original rolls?

**Comment by skymyj** [comment]
I'm sorry. I don't understand the "much to remove (hint), what where the units original rolls?"

**Comment by nixtux** [comment]
There in unneeded code in the current scripts, what purpose where the units in the game you took them from?

**Comment by skymyj** [comment]
All units I took from taesc, I keep the variable and I change 75~100% code after

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
image
New texture.

**Comment by skymyj** [comment]
TLL MM : 
image

**Pull request merged**
