### PR TITLE
Correction Pinchy bug with TowerNano

### PR DESCRIPTION
**Pull request by skymyj**
ATM, all base turn and it's uggly. 
Moreover, the towernano has not enough high. On picture i begin to correct the y axis.
image
And the spray begin before end of active function.
Finally, we had this : 
image
I added new construction texture. If you don't like, i can delte them.

### CODE REVIEW

**Comment by nixtux** [comment]
What was the issue?

**Comment by skymyj** [comment]
Again in work

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
atm :x   
image

**Comment by skymyj** [comment]
image
Done

**Pull request merged**
