### PR TITLE
Add Close / Open MM when it works to new fusion corufus

### PR DESCRIPTION
**Pull request by skymyj**
Add Close / OPen MM when it works.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
Is it safe to merge?

**Comment by ksilversurfer** [comment]
anyway i will test

**Comment by skymyj** [comment]
Yes it's visible.

**Comment by ksilversurfer** [comment]
tested all is fine

**Comment by nixtux** [comment]
So how does a player know the animation is from the MM and not from the fusion running?, @silver why merge?

**Pull request merged**
