### PR TITLE
Fix helepolis error

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Need to upload the cob / bos file to have the dea model.

**Comment by skymyj** [comment]
`#define TA			// This is a TA script

#include "sfxtype.h"
#include "exptype.h"

piece  base, body, housing1, housing2, turret, arms, sleeve, barrel,
       flare, turret3, sleeve3, barrel3, flare3, feetparent, flfoot, frfoot,
       rlfoot, rrfoot, aimpoint;

static-var  Static_Var_1, Static_Var_2, Static_Var_3, Static_Var_4, Static_Var_5;


SmokeUnit(healthpercent, sleeptime, smoketype)
{
	while( get BUILD_PERCENT_LEFT )
	{
		sleep 400;
	}
	while( TRUE )
	{
		healthpercent = get HEALTH;
		if( healthpercent < 66 )
		{
			smoketype = 256 | 2;
			if( Rand( 1, 66 ) < healthpercent )
			{
				smoketype = 256 | 1;
			}
			emit-sfx smoketype from base;
		}
		sleeptime = healthpercent * 50;
		if( sleeptime < 200 )
		{
			sleeptime = 200;
		}
		sleep sleeptime;
	}
}

Create()
{
	set ARMORED to 1;
	Static_Var_5 = 1;
	Static_Var_1 = 0;
	hide flare;
	dont-cache flare;
	start-script SmokeUnit();
	while( get BUILD_PERCENT_LEFT )
	{
		sleep 1000;
	}
}

StartMoving()
{
	signal 32;
	set-signal-mask 32;
	Static_Var_1 = 1;
	while( Static_Var_1 )
	{
		if( TRUE )
		{
			move feetparent to z-axis [-1.] now;
			move flfoot to x-axis [-1.] now;
			move flfoot to y-axis [1.] now;
			move flfoot to z-axis [1.] now;
			move flfoot to z-axis [-1.] speed [1.];
			move frfoot to x-axis [1.] now;
			move frfoot to y-axis [1.] now;
			move frfoot to z-axis [1.] now;
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to x-axis [-1.] now;
			move rlfoot to y-axis [1.] now;
			move rlfoot to z-axis [-1.] now;
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to x-axis [1.] now;
			move rrfoot to y-axis [1.] now;
			move rrfoot to z-axis [-1.] now;
			move rrfoot to z-axis [-1.] speed [1.];
			move body to y-axis [1.] now;
			move body to z-axis [-1.] now;
			move housing1 to x-axis [1.] now;
			move housing1 to y-axis [1.] now;
			move housing1 to z-axis [-1.] now;
			move housing2 to x-axis [-1.] now;
			move housing2 to y-axis [1.] now;
			move housing2 to z-axis [-1.] now;
			turn frfoot to x-axis <-1.> now;
			turn frfoot to x-axis <-1.> speed <1.>;
			turn housing1 to x-axis <-1.> now;
			turn housing1 to x-axis <-1.> speed <1.>;
			sleep 109;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [1.] speed [-1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [-1.];
			turn flfoot to x-axis <-1.> speed <1.>;
			turn frfoot to x-axis <-1.> speed <1.>;
			turn rrfoot to x-axis <1.> speed <1.>;
			turn housing1 to x-axis <-1.> speed <1.>;
			turn housing2 to x-axis <-1.> speed <1.>;
			sleep 110;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [-1.];
			turn flfoot to x-axis <-1.> speed <1.>;
			turn rrfoot to x-axis <1.> speed <1.>;
			turn housing1 to x-axis <1.> speed <1.>;
			turn housing2 to x-axis <-1.> speed <1.>;
			sleep 111;
		}
		if( TRUE )
		{
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [1.];
			turn flfoot to x-axis <-1.> speed <1.>;
			turn rrfoot to x-axis <1.> speed <1.>;
			turn housing1 to x-axis <1.> speed <1.>;
			turn housing2 to x-axis <-1.> speed <1.>;
			sleep 110;
		}
		if( TRUE )
		{
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [1.] speed [1.];
			turn flfoot to x-axis <-1.> speed <1.>;
			turn rrfoot to x-axis <1.> speed <1.>;
			turn housing2 to x-axis <-1.> speed <1.>;
			sleep 111;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [1.] speed [1.];
			move rrfoot to z-axis [1.] speed [1.];
			turn flfoot to x-axis <-1.> speed <1.>;
			turn rlfoot to x-axis <1.> speed <1.>;
			turn rrfoot to x-axis <-1.> speed <1.>;
			turn housing2 to x-axis <1.> speed <1.>;
			sleep 109;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [1.];
			turn rlfoot to x-axis <1.> speed <1.>;
			turn housing2 to x-axis <1.> speed <1.>;
			sleep 111;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [-1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [1.];
			turn rlfoot to x-axis <1.> speed <1.>;
			turn housing2 to x-axis <1.> speed <1.>;
			sleep 110;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [-1.];
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [1.];
			turn frfoot to x-axis <-1.> speed <1.>;
			turn rlfoot to x-axis <-1.> speed <1.>;
			turn housing1 to x-axis <-1.> speed <1.>;
			turn housing2 to x-axis <-1.> speed <1.>;
			sleep 111;
		}
		if( TRUE )
		{
			move flfoot to z-axis [1.] speed [1.];
			move frfoot to z-axis [1.] speed [1.];
			move rlfoot to z-axis [-1.] speed [1.];
			move rrfoot to z-axis [-1.] speed [1.];
			turn frfoot to x-axis <-1.> speed <1.>;
			turn housing1 to x-axis <-1.> speed <1.>;
			sleep 110;
		}
	}
	turn housing1 to x-axis <-1.> speed <1.>;
	turn rrfoot to x-axis <-1.> speed <1.>;
	turn frfoot to x-axis <-1.> speed <1.>;
	turn housing2 to x-axis <-1.> speed <1.>;
	turn rlfoot to x-axis <-1.> speed <1.>;
	turn flfoot to x-axis <-1.> speed <1.>;
}

StopMoving()
{
	Static_Var_1 = 0;
}

RestoreAfterDelay()
{
	sleep 18000;
	set-signal-mask 0;
	turn turret to y-axis <-1.> speed <1.>;
	turn sleeve to x-axis <-1.> speed <1.>;
}

RestoreTertiary()
{
	sleep 9000;
	set-signal-mask 0;
	turn turret3 to y-axis <-1.> speed <1.>;
	turn sleeve3 to x-axis <-1.> speed <1.>;
}

AimPrimary(heading, pitch)
{
	signal 2;
	set-signal-mask 2;
	Static_Var_2 = 1;
	turn turret to y-axis heading speed <1.>;
	turn sleeve to x-axis <-1.> - pitch speed <1.>;
	wait-for-turn turret around y-axis;
	wait-for-turn sleeve around x-axis;
	start-script RestoreAfterDelay();
	return (1);
}

FirePrimary()
{
	explode flare type 128;
	move barrel to z-axis [-1.] speed [1.];
	turn arms to y-axis <-1.> speed <1.>;
	turn sleeve to y-axis <1.> speed <1.>;
	sleep 150;
	move barrel to z-axis [-1.] speed [1.];
	turn arms to y-axis <-1.> speed <1.>;
	turn sleeve to y-axis <-1.> speed <1.>;
}

AimFromPrimary(piecenum)
{
	piecenum = aimpoint;
}

QueryPrimary(piecenum)
{
	piecenum = flare;
}

AimTertiary(heading, pitch)
{
	signal 4;
	set-signal-mask 4;
	turn turret3 to y-axis heading speed <1.>;
	turn sleeve3 to x-axis <-1.> - pitch speed <1.>;
	wait-for-turn turret3 around y-axis;
	wait-for-turn sleeve3 around x-axis;
	start-script RestoreTertiary();
	return (1);
}

FireTertiary()
{
	move barrel3 to z-axis [-1.] speed [1.];
	sleep 150;
	move barrel3 to z-axis [-1.] speed [1.];
}

AimFromTertiary(piecenum)
{
	piecenum = aimpoint;
}

QueryTertiary(piecenum)
{
	piecenum = flare3;
}

SweetSpot(piecenum)
{
	piecenum = body;
}

Killed(severity, corpsetype)
{
	hide flare;
	if( severity <= 25 )
	{
		corpsetype = 1;
		explode base type NOHEATCLOUD;
		explode body type NOHEATCLOUD;
		explode housing1 type NOHEATCLOUD;
		explode housing2 type NOHEATCLOUD;
		explode turret type NOHEATCLOUD;
		explode arms type NOHEATCLOUD;
		explode sleeve type NOHEATCLOUD;
		explode barrel type NOHEATCLOUD;
		explode turret3 type NOHEATCLOUD;
		explode sleeve3 type NOHEATCLOUD;
		explode barrel3 type NOHEATCLOUD;
		explode flare3 type NOHEATCLOUD;
		explode feetparent type NOHEATCLOUD;
		explode flfoot type NOHEATCLOUD;
		explode frfoot type NOHEATCLOUD;
		explode rlfoot type NOHEATCLOUD;
		explode rrfoot type NOHEATCLOUD;
		explode aimpoint type NOHEATCLOUD;
		return (corpsetype);
	}
	if( severity <= 50 )
	{
		corpsetype = 2;
		explode base type NOHEATCLOUD | FALL;
		explode body type NOHEATCLOUD | FALL;
		explode housing1 type NOHEATCLOUD | FALL;
		explode housing2 type NOHEATCLOUD | FALL;
		explode turret type NOHEATCLOUD | FALL;
		explode arms type NOHEATCLOUD | FALL;
		explode sleeve type NOHEATCLOUD | FALL;
		explode barrel type NOHEATCLOUD | FALL;
		explode turret3 type NOHEATCLOUD | FALL;
		explode sleeve3 type NOHEATCLOUD | FALL;
		explode barrel3 type NOHEATCLOUD | FALL;
		explode flare3 type NOHEATCLOUD | FALL;
		explode feetparent type NOHEATCLOUD | FALL;
		explode flfoot type NOHEATCLOUD | FALL;
		explode frfoot type NOHEATCLOUD | FALL;
		explode rlfoot type NOHEATCLOUD | FALL;
		explode rrfoot type NOHEATCLOUD | FALL;
		explode aimpoint type NOHEATCLOUD | FALL;
		return (corpsetype);
	}
	if( severity <= 99 )
	{
		corpsetype = 3;
		explode base type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode body type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode housing1 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode housing2 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode turret type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode arms type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode sleeve type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode barrel type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode turret3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode sleeve3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode barrel3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode flare3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode feetparent type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode flfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode frfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode rlfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode rrfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode aimpoint type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		return (corpsetype);
	}
	corpsetype = 3;
		explode base type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode body type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode housing1 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode housing2 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode turret type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode arms type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode sleeve type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode barrel type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode turret3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode sleeve3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode barrel3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode flare3 type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode feetparent type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode flfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode frfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode rlfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode rrfoot type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
		explode aimpoint type NOHEATCLOUD | FALL | SMOKE | FIRE | EXPLODE_ON_HIT;
	return (corpsetype);
}

`

**Comment by skymyj** [comment]
I understood erros. 
All numbers are to 1.
I will change them to have good movement.

**Comment by skymyj** [comment]
Question : how change the tll logo on 3do model ?

**Comment by skymyj** [comment]
All fixed now. (Except logo TLL)

**Comment by nixtux** [comment]
You uploaded new model file, what did you change and why?

**Comment by skymyj** [comment]
I edit many name-function, to have same than other units.
I added new values for legs movement. Less slow.
I changed many variables to check with 3do model.
I added the good type for killed function.

**Comment by skymyj** [comment]
The new model file is the wreckage unit. Didn't exist. 
I changed the object name to have a better sense.

**Comment by skymyj** [comment]
I dowloaded the upspring, but didn't find how fix core logo.

**Pull request closed without merging**
