### PR TITLE
Change Model for TLLMEX

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Vote n, that's a messy way of doing it.

**Comment by skymyj** [comment]
Nix. You speak about model to rename ? 
Or for the global idea ?

**Comment by nixtux** [comment]
the basic model should always be the original model.

**Comment by ksilversurfer** [comment]
not sure about this...

**Comment by skymyj** [comment]
Well. I close this request.

**Pull request closed without merging**
