### PR TITLE
Balance damage for capital mini

### PR DESCRIPTION
**Pull request by skymyj**
4500 dmg/s is too op cause of 2 burst.

### CODE REVIEW

**Comment by Antarac** [comment]
I needed to read this really often before i understood it =)
If you explain pull requests more detailed
chance is higher that people comment it.
Nobody comment stuff he wont understand. 
And Nixtux asked for it in issue #294 also.

I would agree to make capital aa weaker but
all changes look so speculative cause i don't
see how you get to that new values except
they are lower ofc.

**Comment by skymyj** [comment]
What to say. It's hero Aa weaoon.
If you make calcul, 2 laser turret inflicts 2000 more damage per seconds.
It's too much imho. When I balanced these weaoon 2 years ago, didn't see the 2 bursts... an it's hard to see in testing. So its entierely by feelingandby seeinggame than I can adress this commit.

**Comment by Antarac** [comment]
I tried big attacks with Bombers and it were no threat for Capitals.
So for me we can make it weaker and see how it behaves.

**Comment by ksilversurfer** [comment]
i agree hero AA weapon is too strong.

**Comment by skymyj** [comment]
See #343

**Pull request closed without merging**
