### PR TITLE
Explosion Balance

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
We have to balance things => for example, if I saw a commander with my hero. I can autodestroy and kill him, cause no special damage vs commander :X 200K in commander at 1250 range

**Comment by skymyj** [comment]
So, 2 differents thing : 

Explosion from death :  nuclear missile, nuclear missile2, megablast
=> low damage vs commander : 2.5K
=> low range (600 for krog, 700 for krog1, 900 for Hero)
=> Damage at 10K - 30K (Hero)

Explosion from autodestroy : Bantha_nuke,, crblmssl, crblmssl4, megablast1
=> High damage vs commander : 2.5K - 7.5 K (Hero)
=> Medium range (900 for krog, 1000 for krog1, 1150 for Hero)
=> Damage at 10K - 60K (Hero)

**Comment by Antarac** [comment]
I closed issue #297 "Hero Explosions" and moved the text i wrote here.

Most Heros just need to move deep into enemys base and
the giant explosion leads to extinction of the whole base usually.
It doesn't really matter how much firepower they have.

I would suggest to make a few small explosions, and then
a last one that is a bit bigger, but ofc not as big as it is now.

With some random variables for time, explosion size and amount
combined with limits for it would make it look not same all time.
So for example between 1 and 5 seconds time,
2-7 small explosions and anyway the end explosion.

It's more realistic and would look better to have
several small explosions and a final detonation.

That comes closer to reality that first blow up some ammunition
depots and fuel tanks of units before the whole thing blows up.

Most important thing is, that you need a few
Heros to blow up, to wipe out a base completly.

Firepower of ships gets more important if
explosion doesn't kill the enemy straight away.

Game in T4 stage could last longer and chance is
higher other T4 units get used in the game.

**Comment by ksilversurfer** [comment]
I like the idea of nerfing explosions  !

**Comment by nixtux** [comment]
Why do crawling bombs now get a massive reduction in damage from explosion?

**Comment by skymyj** [comment]
Well, no reduction because it's crawling explosion. 
Damage has  ot been reduced vs commander.

**Comment by nixtux** [comment]
Bantha nuke for example, why did you add it there?

**Comment by skymyj** [comment]
Indeed. On comments, I explain, that kill a big unit, make less damage for commander. 
Instead the autodestroy.

I think, we have to create a Wiki or integrate rules/advices in the wiki. 
For example, the autodestroy feature. How much damage for each unit...
So we need to make easy laws to help players. Actually, there are too much differents damage rules. For example, starburst launcher. I think, we need to have all the same values (range / damage) at samae level (T3 / T3.5 / T4)

**Comment by nixtux** [comment]
Atm with the extra crawlbomb damage class there is the potential for them to survive units exploding which in turn would be OP

**Comment by ksilversurfer** [comment]
that changes will make crawling bombs too OP in certain situations.
200..150 dmg from blast.... too small.
Anyway adding new special damage called "crawlingbombs" will make game even more complex!!!
I like to keep settings/options simple.

I vote 100% NO !

**Comment by ksilversurfer** [comment]
However i agree to nerf explosions of certain units like Hero or Valiant - vote yes here

**Comment by ksilversurfer** [comment]
And again pls dont mix two changes in one topic, its confusing.
i mean - first change nerf explosions
second making crawling resistant to explosions

**Comment by nixtux** [comment]
Remove special crawling bomb damage then i will merge

**Comment by skymyj** [comment]
Change Done.  #342
Is it possible to merge this request : https://github.com/techannihilation/TA/pull/342
I can't and I don't know why.

**Comment by nixtux** [comment]
No not merging,  there is still special damage for crawling bombs

**Comment by skymyj** [comment]
I delete all damage I added for crawling bomb.
There are 2 values already existing : crawl_blast & crawl_blastsml.
Wee have to keep these 2 values : cause, they are explosion from crawling_bomb themselves.
If one is killed, all explose. It's too much fragile/brittle. It's like all mines : there is special rules to dodge than all explodes.

**Pull request closed without merging**
