### PR TITLE
Increease Scale Colossus

### PR DESCRIPTION
**Pull request by skymyj**
And balance energy ratio.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
Skymyj this are collision boxes (purple)
https://snag.gy/4usXrt.jpg

By default unit collision box is a sphere of model size, some units like llt need other collsion like cuboid
or ellipsoid shape for commander.

If you collsion box is NOT defined then its default sphere.

Colossus can have sphere, becouse his shape allow it.

so pls remove that lines:
		collisionvolumeoffsets = "0 -5 -3",
 +		collisionvolumetest = 1,
 +		collisionvolumescales = "220 320 180",
 +		collisionvolumetype = "Ell",

**Comment by ksilversurfer** [comment]
just remove that lines, all rest is ok, I tested

**Comment by skymyj** [comment]
Understood :)

**Comment by ksilversurfer** [comment]
good now you need check footrprint

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
Rework mvt class and foot

**Pull request merged**
