### PR TITLE
Add leopard

### PR DESCRIPTION
**Pull request by skymyj**
image

### CODE REVIEW

**Comment by nixtux** [comment]
It's it a t3 unit?

**Comment by nixtux** [comment]
I this tested?, please check particle count!!!

**Comment by skymyj** [comment]
T2 uniut. Same strong then turtle 2.5

**Comment by nixtux** [comment]
For better visual effect as its a burst weapon use shotX for emit-sfx instead of fireX

**Comment by skymyj** [comment]
I would have the same effect than armraven (catapult T3 core). 
I saw that there is a shot function. I will check that

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
Done

**Pull request merged**
