### PR TITLE
Change Unit Description

### PR DESCRIPTION
**Pull request by Antarac**
I vote for calling the Mobile Anti-Nuke Units
in description also "Anti-Nuke System"
instead "Anti-Missile Defense".
It will be for sure lesser confusing and got
more of a straigt line since there are so many.

If you accept the change for "Hedgehog"
i will start pull requests for "Turtle" and
"Scarab" also.

"Hedgehog - Mobile Anti-Missile Defense"		Core T2 Vehicle
"Turtle - Mobile Anti-Missile Defense"			TLL T2 Kbot
"Scarab - Mobile Anti-Missile Defense"			Arm T2 Kbot

"Hive - Aircraft Carrier with Anti-Nuke"			Core T2 Ship
"Giant - Aircraft Carrier with Anti-Nuke"			TLL T2 Ship
"Colossus - Aircraft Carrier with Anti-Nuke"		Arm T2 Ship

"Fortitude - Anti-Nuke System"				Core T2 Building
"Peacemaker - Anti-Nuke System"				TLL T2 Building
"Protector - Anti-Nuke System"				Arm T2 Building

"Long Range Fortitude - Long Range Anti-Nuke System"	Core T2.5 Building
"Long Range Peacemaker - Long Range Anti-Nuke System"	TLL T2.5 Building
"Advanced Protector - Long Range Anti-Nuke System"		Arm T2.5 Building

"T3 Defensor - T3 Anti-Nuke System"			Core T3 Building
"T3 Gazelle - T3 Anti-Nuke System"				TLL T3 Building
"T3 Protector - T3 Anti-Nuke System"			Arm T3 Building

### CODE REVIEW

**Comment by nixtux** [comment]
Yeah i agree with this change, if you can do all changes in this one commit please

**Comment by skymyj** [comment]
We need good description for many of units ! 
+1 like

**Comment by ksilversurfer** [comment]
Good job !

**Comment by Antarac** [comment]
Now there are commits for "Hedgehog",
"Turtle" and "Scarab" in this pull request.

**Comment by nixtux** [comment]
What about Upgraded versions?

**Comment by Antarac** [comment]
Added "Long range Scarab" and "Long Range Hedgehog".

**Pull request merged**
