### PR TITLE
Balance T4 armraptor.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
i need take closer look here and test that changes in game

**Comment by skymyj** [comment]
These Kbot kill so easely a Bantha at 10KM. 
So, we have to increase the cost to 18-19K. 
More over, there are really commander hunter with long range

**Comment by ksilversurfer** [comment]
tested in game, i think that changes or not bad i can agree
vote yes

**Comment by skymyj** [comment]
All started with corheaven. This unit didn't have special damage vs commanders. Other units with same range had reduced damaages. 

So, we have to adjust. 
Silver said in BA, there is no reduced damage and commander is weaker than TA. 

So, 3 options for me : 
- Delete reduced damage for all range (T3 unit at 1300)
- Do nothing except add special damage for Corheaven
- Special damage for missile at 66 or 75%. Plasma no special damage cause commander have shield

**Comment by ksilversurfer** [comment]
maybe like that:
everything under 1300 - delete special damage
everything above 1300 - set special damage to 66%
fast units like razorback - set special damage to 50%

**Comment by skymyj** [comment]
Well I'm for. 
I just add : 
everything plasma over 1300 - set special damage 66%
everything laser / lighting / missile over 800 - set special damage 50% 
Fast units with laser / lighting / missile over 1.6 velocity and over D-Gun range - set special damage to 50%

**Comment by ksilversurfer** [comment]
to be fair lets make 50/50 of yours idea and mine:

everything plasma over 1300 - set special damage 70%
everything laser / lighting / missile over 1000 - set special damage 60%
Only fast units with laser or lighting  - set special damage to 50%

:) ?

**Comment by skymyj** [comment]
You are an expert in negotiation :)

My last offer :)

everything plasma over 1300 - set special damage 70%
everything laser / lighting / missile over 900 - set special damage 66% (900 for sniper and mobile Tachyon)
Only fast units with laser or lighting or missile - set special damage to 50% (missile for karg)

**Comment by skymyj** [comment]
In thinking more, it will be impossible to change all unit with special damage.
If I take sumo, 700 range and special damage vs commander. (70%)
And there are so many other units..

**Comment by ksilversurfer** [comment]
>  You are an expert in negotiation :)
> 
> My last offer :)
> 
> everything plasma over 1300 - set special damage 70%
> everything laser / lighting / missile over 900 - set special damage 66% (900 for sniper and mobile Tachyon)
> Only fast units with laser or lighting or missile - set special damage to 50% (missile for karg)

Agree vote YES :D

**Pull request merged**
