### PR TITLE
Update corlevlr.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Deleted damage vs com

**Comment by ksilversurfer** [comment]
corlevlr1 - not nerfed too much ?
range = 375, - > range = 350,
damage default = 345, -> default = 280,
areaofeffect = 180, -> areaofeffect = 160,

imo its heavy nerf for this unit... not sure if it will be worth to morph now from normal Leveler

**Comment by skymyj** [comment]
corlvlr1 is really to OP. 
This unit can kill every thing at range 375. Even battle com don't resist.
I you compare it vs the corlvlr, there is already many boost even with nerf.

**Comment by ksilversurfer** [comment]
Maybe like that? :)

damage default = 300 (corlvlr has 280)
areaofeffect = 170 (corlvlr has 160)
weapon range = 325 (same as corlvlr)
maxdamage = 1600 ( corlvlr has 1275)
reloadtime = 2.2 ( corlvlr has 2.5,)

**Comment by skymyj** [comment]
damage default = dont touch
areaofeffect = Done
weapon range = done
maxdamage = Done
reloadtime = Dont touhch

**Comment by skymyj** [comment]
136,454534254 dmg / S vs 140 with my config.
I prfer round up :)

**Comment by ksilversurfer** [comment]
ok :D vote yes

**Pull request merged**
