### PR TITLE
Riot Arm Balance

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Dont touch featuredefs, ie dead/heap there autogenerated so leave alone, i wont even look at ant more pr if you keep changing these values.

**Comment by skymyj** [comment]
Done

**Comment by ksilversurfer** [comment]
Please compare to BA values:
https://pastebin.com/dnqw01TE

armjanus in TA is weak...
and again BA dont have special dmg vs commanders

Ofc we dont need make same as in BA but lets try balance with reasonable values :P

**Comment by skymyj** [comment]
I increased power of Janus.
I can delete commanders damage.

**Comment by ksilversurfer** [comment]
yes pls make more in BA direction

**Comment by skymyj** [comment]
Deleted damage vs com

**Comment by Antarac** [comment]
Can i see ingame somewhere if a Unit does extra damage to Commander?

**Comment by nixtux** [comment]
Yeah select unit press space bar

**Comment by ksilversurfer** [comment]
vote yes

**Comment by skymyj** [comment]
Done

**Comment by ksilversurfer** [comment]
vote yes ! :)

**Pull request merged**
