### PR TITLE
Add Corgol1 Armbull2 for engineerer Commander

### PR DESCRIPTION
**Pull request by skymyj**
Signed-off-by: skymyj <skymyj@hotmail.com>

### CODE REVIEW

**Comment by skymyj** [comment]
Add Adv bulldog & Adv Goliath for Engeneerer.
Add limitation of Tech Center 2. 
the version 1 could morph into 2 with XP or with builder from the battle commander

**Comment by pcdummy** [comment]
Call for votes.

**Comment by nixtux** [comment]
Yes from me

**Comment by skymyj** [comment]
Ok. 2 votes with yes. I merge.

**Pull request merged**
