### PR TITLE
Add T3 Metal extractor for Arm/Core to test

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Sorry but we don't want the same model on each faction

**Comment by skymyj** [comment]
Its not the same model. See #729

**Comment by nixtux** [comment]
Can we have link to which pics here please

**Comment by nixtux** [comment]
What about tll?

**Comment by skymyj** [comment]
[mex.zip](https://github.com/techannihilation/TA/files/1663248/mex.zip)

**Comment by skymyj** [comment]
For TLL, I have 2 options : 
- Take T2 existing and change texture and increase scale.
- Create model between T2 and T4 Mex.

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
#675

**Comment by nixtux** [comment]
ota icons ?

**Pull request merged**
