### PR TITLE
Fix Autoheal for arm_furie.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Why?, he seems buff enough as he is?

**Comment by skymyj** [comment]
all unit have +5. His balance didn't take the facto of +7

**Comment by nixtux** [comment]
Nope not all units, I think it's fine as it is

**Comment by nixtux** [comment]
Eg check high level commanders, this unit for one https://github.com/techannihilation/TA/blob/master/units/armpraet.lua#L31

Imo it's logical for larger units to take longer to start healing please leave well alone

**Pull request closed without merging**
