### PR TITLE
Balance T4 Battle Units

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
exoarm is ver hard to balance. 
Do you will increase size ?
I think, we have to increase more T4 Lab (Hexapod and shied).

If you want to have praetorian and moonkeylord in T4 lab, we need to increase stats. Cause they are T3.5 today. For me, we should deleted praetorian (no very nice unit and same job than exoarm). Or delete exoarm.
I repeat, but IMHO, we should make them T3.5 units.
T3 : 10K M spent
T3.5 : 35KM
T4 : 90K

Maybe we could have unit at 60-70 K M.

**Comment by nixtux** [comment]
Ive increased size of exoarm

**Comment by nixtux** [comment]
i agree praetorian is not right but for now he needs to stay, i will increase size of that units, but imo all old t4 are way to big, they should have there sizes reduced a bit

**Comment by skymyj** [comment]
Ok for Exoarm. I think, you shouldn't loose time to reduce size. Size is good for me.

**Comment by skymyj** [comment]
You will add plasma shield for Exoarm ?

**Pull request merged**
