### PR TITLE
Small Core Shield - buildtime balance

### PR DESCRIPTION
**Pull request by ksilversurfer**
price is ok.
build time too high !
Reducing by 45% of normal core shield buildtime = 57166, = 25724

### CODE REVIEW

**Comment by nixtux** [comment]
Can I have arm small shield in the same pr?

**Comment by ksilversurfer** [comment]
yes ok

somthing is wrong: 
core small shield 
buildcostenergy = 8533,
buildcostmetal = 1920,
 
but Arm small shield 
buildcostenergy = 8533,
buildcostmetal = 1493,

what to do?
increase arm cost to 1920 or both arm/core to 1700?

both shields have same power and hp

**Comment by ZweisteinT** [comment]
Both at 1920 :) I think they are quiet powerful and should not cost only half as a punisher :)

**Comment by nixtux** [comment]
A slight variation in values please

**Comment by ZweisteinT** [comment]
1723 and 1936...

**Comment by ksilversurfer** [comment]
done buildtimes from normal arm and core shields (45%)

**Comment by nixtux** [comment]
Can we vote on https://github.com/techannihilation/TA/issues/276

**Pull request merged**
