### PR TITLE
Balance Storage E for adv Fus only

### PR DESCRIPTION
**Pull request by skymyj**
The storage is very OP on these structures.
Small change maybe not at good time, but it should be accepted.

### CODE REVIEW

**Comment by Antarac** [comment]
As i said for first energy storage pull request,
i like the idea to give storage more reason to exist.
But people are so used to the storage concept
since long time that they won't accept it.

Chance that this will fail is even higher cause last
change failed short time ago. Some people will
feel fooled if it comes again now in other form. 
Others will even complain more why same "mistake"
comes again so quickly. That gives lot of space for
people that like to complain about TA.
Skip the change to avoid negative chat about TA.
Humans are just creatures of habit and the best PR
can fail due to this and drive people nuts.

**Comment by skymyj** [comment]
See value on ba.
Im ok to let value but we will adjust  cost.

**Comment by Antarac** [comment]
I actually give a shit what they do in BA =)
I think it's the wrong way to compare it.
That implys somehow that BA is better
than TA and i don't think so.

Can you make a new Issue please for cost
since i don't know why to change cost now.

**Comment by Antarac** [comment]
I'm sorry Skymyj!
What i said about BA was to extreme.
Ofc we can take best things of other
games and implement it into TA.

**Comment by ksilversurfer** [comment]
pls dont change storages for fusions, I not agree becouse ppl will moan a lot

**Comment by nixtux** [comment]
Yeah way too big a change, I won't be merging this

**Pull request closed without merging**
