### PR TITLE
Balance T1.5 Plasma and Shield

### PR DESCRIPTION
**Pull request by skymyj**
ATM, we have : 
T1.5 Shield (8,5KE 1.7KM) vs T1.5 Plasma (36KE 2.3KM)
T2   Shield (66KE 3.7KM) vs T2 plasma (65KE & 4,3KM)
T3  Shield (132KE 13KM) vs T3 plasma (200KE & 18KM)

### CODE REVIEW

**Comment by skymyj** [comment]
It shows that : 
- T1.5 Shield are OP with very low energy cost.
- T3 Shield could cost higher
Energy cot is equal. But less metal for Shield vs Bertha. I'm ok with that.

**Comment by ksilversurfer** [comment]
not rly OP, T1.5 shieldpower is low, very easy to break it.
If you increase energy cost to 30k it will be very hard to build it !!!
Increase T1.5 Shield Ecost max to ~14k
Reduce T1.5 Plasma Ecost to ~22k

Its hard afford T1.5 Plasma or T1.5 Shield with T1.5 eco
We see those weapons very rare in games !

**Comment by skymyj** [comment]
Ok. I will more balanced them.
T1.5 and T3 are ok so. 
I will change Ratio  for T2 to balance with other.

**Comment by ksilversurfer** [comment]
Looks better

**Comment by skymyj** [comment]
Ok for me. 
I balanced explosion too for Sield and Plasma. (explosion / autodestroy) 
T1.5 : mini crawlblast / crawlblast
T2 : Crawlblast / Nuke Mine
T3 : Mini Nuke Mine / Bantha Explsosion

**Comment by skymyj** [comment]
Same for Timebuild. changed for T3 Shield. 200000 now.

**Comment by ksilversurfer** [comment]
Nixtux agree?

**Pull request merged**
