### PR TITLE
Attacking Gunships and Choppers hit each other

### PR DESCRIPTION
**Pull request by Antarac**
If big groups of choppers or gunships attack the
same target, flying in cirlces around it, they shoot
each other and die more quickly.

Started with this Plane and will
add others too if its allright.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
yes will fix it collidefriendly = false,

what about add aslo avoidFriendly= false, - to boost them or it will look unreal? (now is true becouse default is)

Pls comment

**Comment by nixtux** [comment]
collidefriendly = false  +  avoidFriendly= false would be the best bet

**Comment by nixtux** [comment]
this need to happen for all choppers before a release is done

**Comment by skymyj** [comment]
and what about delete all copters ? :)

**Comment by nixtux** [comment]
Nope

**Comment by Antarac** [comment]
Check if these changes are allright and i will keep going.

**Comment by Antarac** [comment]
Made "corcom6" update in the wrong pull request and i dont know how to delete it.

**Comment by nixtux** [comment]
Yeah just do all copter + gunships

**Comment by nixtux** [comment]
I'm not sure armjade needs it, ie any laser type weapon

**Pull request merged**
