### PR TITLE
 Liche (armcybr) - Boost Hp by 30%, Increase cost by 40%, Reduce spee…

### PR DESCRIPTION
**Pull request by ksilversurfer**
It is T2.5 unit, so i think that can be good idea
pls vote :P

### CODE REVIEW

**Comment by nixtux** [comment]
Mass should be math.max(ud.maxdamage / 6.0, ud.buildcostmetal)

**Comment by skymyj** [comment]
I'm for increase tis unit. 
I'm a problm with energy use. Is it possible to have 0 in production and use ? 
But to add a cost when shooting ? Like 2kE / Shooting.

**Comment by ksilversurfer** [comment]
_Is it possible to have 0 in production and use ?_ - yeah 
_But to add a cost when shooting ? Like 2kE / Shooting._ - nah, it will confuse ppl, why it not shooting!!? :D

**Comment by skymyj** [comment]
Maybe in adding in description. Like : 
- description = "Atomic Bomber [2.5KE per Shot]",

**Pull request merged**
