### PR TITLE
Balance Storage Commander

### PR DESCRIPTION
**Pull request by skymyj**
Goal : double Energy Storage by level. And Add +1000 Metal storage by level
Standar/Battle/Assault : 1KE / 1KM
Eco : 2KE / 2KM
Fusion : 4KE / 3KM
Star : 8KE / 4KM
Supreme : 16KE / 5KM

### CODE REVIEW

**Comment by ksilversurfer** [comment]
I vote no here, storages are ok now, dont need to be changed in my opinion

**Comment by skymyj** [comment]
The thing is : Metal storage are builded for defense :X 
Nobody needs this storage. Sometimes player builded it to reclaim the T3 lab.

I think, we really should decrease all storages. It's not evil to have to build a 200Metal structure if you want reclaim commander wreckage or T2 lab on battlefield.

But commander and before the MEX counter this.

**Comment by ksilversurfer** [comment]
i need rethink that :D

**Comment by Antarac** [comment]
Another complicated Storage Issue :O 
I need to think about it too.

**Comment by Antarac** [comment]
Why is it merged already?
To me this is not figured out yet.
Also i see no connection between
this and the metal storage walls.

**Comment by skymyj** [comment]
Yes it is. And sinc 1 week, i saw players make these structures.

**Comment by Antarac** [comment]
Well, i didn't notice that change really while playing.
But it changed nothing about building storage for wall i think.

**Comment by skymyj** [comment]
It written in infolog.

**Pull request merged**
