### PR TITLE
Proposition Change Weapon monkeylord.lua

### PR DESCRIPTION
**Pull request by skymyj**
ATM, this weapon is uggly imo and the sound is so loud.

I propose like Hero Spider to integrate the final beam weapon : accelerator beam.

Same balance.

### CODE REVIEW

**Comment by nixtux** [comment]
Not ugly imo, and its different, using the same effect all the time is not desired, just alter sound volume imo

**Comment by ksilversurfer** [comment]
i dislike too weapon of monkeylord, but Nixtux is master : )

**Comment by nixtux** [comment]
If you want to change weapon make a new effect, no copy and pasting

**Comment by ksilversurfer** [comment]
yea color change can be ok

**Comment by skymyj** [comment]
I have to think again to this.

**Pull request closed without merging**
