### PR TITLE
Boost weapons of AK X-1

### PR DESCRIPTION
**Pull request by ksilversurfer**
Comparing to 3 Sumos :
3 sumos price: 6465m (3x2155m) and 99000e (3x33000e)
sumos range: 650

AK X-1 price: 7540m and 100800e
AK X-1 range: 2 weapons 600 and rocket 850
ITS T2.5 unit! (you need also RC T2.5... ( another 5000m) )

now it can kill 3 sumos 
(AK X-1 hp after killing 3 sumos ~12%)

### CODE REVIEW

**Comment by pcdummy** [comment]
Good to go.

Have seen test fights of AK vs. Sumo, was easy for Sumo to win.

**Comment by nixtux** [comment]
+1

**Comment by smurfpro** [comment]
Big AK is too shitty for nay use. So i vote for boost.

**Comment by skymyj** [comment]
I vote NO (a big fat No from Nixtux expression ^^ ).
I explain : You should compare with KrogTsar.
Krogtsar and Ak are good balanced. If you boost Ak, you have to boost Krog...
I tested with 2 corcumo (4250m) vs Krogstar (6k). Krog win at 10% hp left.

I think the problem is Sumo. If you compare with tllbind (cost >3km)....... 
I think, the best is : 
 - to reduce the precision with sightdistance = 510 => 400.
 - Increase metalcost from 10% for CorSumo and Sumo1

**Comment by ksilversurfer** [comment]
I not agree with that skymyj.

**Comment by nixtux** [comment]
Imo krogtaar is a bit weak also, I did a massive nerf a while ago, and since then there has been 2 more nerfs.

**Comment by ksilversurfer** [comment]
yep i said some time ago that krogtaar is alos too weak now

**Comment by skymyj** [comment]
I think, we have to take the speed balance too. 
It's logic than an unit at move 0.75 are better than other to 1 (Akx speed) or more (1.2 krog speed)) at same price.

Each unit has a function. You can rush with sumo. But give more time for opponent to make appropriate defense.
Other example : If you take 4 sumos, I can kill easely them with the Akx. All depends the skill of players. If you can manage your Akx, easy to shoot at long range with large Aoe before they shoot you. You have a better speed too to manage distance.

**Comment by skymyj** [comment]
So finally, don't balance for player who make only porcing.

**Comment by ksilversurfer** [comment]
as i said in lobby, i cant do much here, skymyj balance all shit alone... 
happy balancing and nerfing units... (ups, sorry crippling the arm units i mean)

If i ask to boost weapon, now he nerf speeed lol thx, bye

**Comment by skymyj** [comment]
Well I m sorry. I think we all have to make requests to balance the game.

So i vote Y but i'm waiting a balance for tsar too.

Then, when i done a balance, i try to make round number between damage and reload. I'm waiting a widget damage like Ba or pa with show all damage description.

**Comment by skymyj** [comment]
`as i said in lobby, i cant do much here, skymyj balance all shit alone...
happy balancing and nerfing units... (ups, sorry crippling the arm units i mean)

If I ask to boost weapons, now he want nerf speeed lol thx...`

Silver, I just want to say my opinion. Now there were 2 votes Yes (Dummy and Nix). 
So I just accept the decision of the team :)

**Comment by ksilversurfer** [comment]
ty skymyj :)))

**Comment by nixtux** [comment]
is this ok to merge now ?

**Pull request merged**
