### PR TITLE
Add new model for Chainsaw upg

### PR DESCRIPTION
**Pull request by skymyj**
Done

### CODE REVIEW

**Comment by nixtux** [comment]
Can you upload images of new units v old

**Comment by skymyj** [comment]
image

**Comment by nixtux** [comment]
My old issue is reduced barrel count on upgraded version, imo it does the fit the bigger and better model we currently use

**Comment by skymyj** [comment]
Ok. So what do you want i change ?

**Comment by skymyj** [comment]
I'd like to rework them and reduce Z size  for barrel. Missile didn't need long barrel

**Comment by skymyj** [comment]
For the Core, I will let the model ATM, and add 2 barrels for adv

**Comment by nixtux** [comment]
Reopening as posted before feature freeze

**Comment by skymyj** [comment]
With this model, is it ok ? https://cdn.discordapp.com/attachments/431389653174845441/461245726912020501/unknown.png

**Comment by skymyj** [comment]
image
On picture, the 2 flare are hidden with bos.

**Pull request merged**
