### PR TITLE
Balance ALL T2 CONS

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
#222

**Comment by skymyj** [comment]
Can I continue to change all T2 ?

**Comment by skymyj** [comment]
35% decrease on Metal Cost.
Decrease HP to fix at ~1700
TLL Less decrease to have good Ratio with TLL vs ARM/CORE

**Comment by skymyj** [comment]
I'm waiting you approval to continue with Naval, turtle, sea air

**Comment by nixtux** [comment]
Make a new Pr for nanos changes

**Comment by skymyj** [comment]
Revert Done. 
Work Done. 

There was many unbalanced stats on many units. 
Hover time at 40K for example and many other.
I increased time for Adv Sub too at 25K (Same than Air). Maybe I should increase more, cause production power is better for Naval ?

**Comment by ksilversurfer** [comment]
i agree with that changes

**Pull request merged**
