### PR TITLE
Add Upg Fatboy to Ditawn (Combat Commander builder)

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
To be fair vs core

**Comment by ZweisteinT** [comment]
I thought sumo is equivalent? 
To be fair both combat commanders should have an equal good unit to build

**Comment by skymyj** [comment]
Well I thought yesterday to that :)

My opinion : Delete the helldriver and the escort t2.5 by Fatboy1 and Sumo1

**Comment by ksilversurfer** [comment]
Sumo1 ? - is a core unit

**Comment by skymyj** [comment]
delete helldriver for FatBOY for Arm.
delete Escort Kbot for CorSumo1 for Core

**Comment by ksilversurfer** [comment]
so arm Fatboy1 will need Rc2 ??
but core Goliath not?

**Comment by ksilversurfer** [comment]
Fatboy1 need rc2 , core Goliath dont need
Coresumo1 need rc2 , armbull2 not (pitbull tank)

I **cant** accept that.

**Comment by skymyj** [comment]
I merged yesterday. They need both RC2

**Comment by ksilversurfer** [comment]
you seriousy kidding me...

**Comment by skymyj** [comment]
I spoke about Goliath and Armbull1

**Comment by skymyj** [comment]
But If you want to delete them, why not

**Comment by ksilversurfer** [comment]
i want repleace only 1 unit to have fatboy1 in arm

**Comment by ksilversurfer** [comment]
thats all

**Comment by ksilversurfer** [comment]
Skymyj can you accept maybe that:

Fatboy1 **need rc2** , core Goliath **need rc2**
Coresumo1 **need rc2** , armbull2 **need rc2**

Sounds now more balanced

**Comment by skymyj** [comment]
Yes :)

**Comment by ksilversurfer** [comment]
Cooool :D

**Pull request closed without merging**
