### PR TITLE
Remplace model tllvhlt.3do

### PR DESCRIPTION
**Pull request by skymyj**
New textures for Vhlt.

### CODE REVIEW

**Comment by skymyj** [comment]
image

**Comment by nixtux** [comment]
Can you show compare to old texture (atm the graidant texture on cross body looks out of place)

**Comment by skymyj** [comment]
Yes indeed. I will change

**Comment by skymyj** [comment]
New texture for cross : 
image

**Comment by ksilversurfer** [comment]
pls provide old texture to compare with new

**Comment by nixtux** [comment]
In that pic above the shaded section between the team color on main arm looks out of place

**Comment by skymyj** [comment]
you damm right nix. 
Fixed

**Comment by nixtux** [comment]
Can I see updated pic?

**Comment by skymyj** [comment]
sure : 
image

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
ATM : 
image

**Comment by nixtux** [comment]
After checking out ingame I prefer the old textures

**Pull request merged**
