### PR TITLE
Delete Anti T3/T4 weapon from T2

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
In working.

**Comment by skymyj** [comment]
#514

**Comment by nixtux** [comment]
Nope don't add nanos

**Comment by skymyj** [comment]
Finished for Delete corboucher, nebraska and tlldmc. 
Do you want I add T2 Nano ?

**Comment by skymyj** [comment]
ok. You can merge

**Comment by ksilversurfer** [comment]
1000% agree i like that idea very much. 
But without nanos ofc. Nanos should be only morphed.
Exception fot T4 is acceptable

**Comment by skymyj** [comment]
Some playefs ask me why theh ar locked. We need to unlock them.

**Comment by nixtux** [comment]
One after this change which cons can build anti t3/t4 weapons, Two can't merge anyways due to conflicts

**Comment by skymyj** [comment]
T3 cons can already make these structures. 
Due to  the high cost, it is make sens to build heavy cons for heavy structure.

**Comment by skymyj** [comment]
We could open for t4 cons too

**Comment by skymyj** [comment]
Conflicts resolved.

**Comment by nixtux** [comment]
So t3 kbots only?, so we have gone from tank/kbots/air to making them only buildable by kbots

**Comment by skymyj** [comment]
Well like I said in my last post, we need to add t3 veh cons for all faction. And maybe ship and air.

**Comment by nixtux** [comment]
I know but atm what I'm saying is this seems like a step back not forwards, limiting anti weapons to kbot only unless your higher tech and by the time your higher tech bringing them to the party when it's over is pointless.

**Comment by skymyj** [comment]
Ok. So in stand by until new T3 Cons.

**Comment by ksilversurfer** [comment]
yes we need T3 veh cons

**Pull request closed without merging**
