### PR TITLE
T2 Stationary Flaks Rebalance/Nerf

### PR DESCRIPTION
**Pull request by ghost**
```
- 25% firerate
- 10% range (tll -7%, becouse metal cost is x2, it has better dps but should have range bonus too)

tllflak increase buildtime 13995 -> 26435
```

### CODE REVIEW

**Comment by skymyj** [comment]
I vote No. At least decrease damage by 33% with this reload and aoe.
Too much for 1K Metal vs all other aa def.

**Comment by ksilversurfer** [comment]
ok so nerf firerate only, and keep dmg as was?

**Comment by skymyj** [comment]
I'm for

**Comment by skymyj** [comment]
But don't forget to nerf T3 Flak too.

**Comment by ksilversurfer** [comment]
At the moment we need nerf only T2 Stationary Flaks

**Comment by ksilversurfer** [comment]
one thing what I dont understand here is buildtime for tllflak, 
Tllflak cost way more than core or arm, but build time is way lower, is it ok?

**Comment by skymyj** [comment]
Sure. There are no balanced other values.

**Comment by ksilversurfer** [comment]
_skymyj commented_
`it's not 25% but 20% firerate less.`
??
adding 25% to reloadtime (e.g. 0.3 *1.25 = 3.75)

**Comment by skymyj** [comment]
You are right. I would talk about damage /s . 
1600 / 2000 = 20%

**Comment by ksilversurfer** [comment]
BA armflak values:
`
buildcostenergy = 13000,
buildcostmetal = 820,
maxdamage = 1575,
areaofeffect = 192,
range = 775,
reloadtime = 0.55,

damage = {
		bombers = 250,
		fighters = 500,
		vtol = 250,
	},
`
TA armflak values:
`
buildcostenergy = 38400,
buildcostmetal = 1045,
maxdamage = 2800,
areaofeffect = 192,
range = 975,
reloadtime = 0.3,

damage = {
	 bombers = 600,
	 default = 5,
	 fighters = 600,
	 flak_resistant = 200,
	 unclassed_air = 600,
	},
`

**Comment by skymyj** [comment]
Yes. Ta stats are OP. 
At least, range 775 are good for me. With 1500dmg/s and 192 aoe.

**Comment by nixtux** [comment]
My vote is for reload at .45 and damage at 900 == dps of 2000 (same as current dps), aoe at 192 and no more than a 10% reduction in range 900 to 810

**Comment by ksilversurfer** [comment]
Yes agree with Nixtux, its a good start.

**Comment by ksilversurfer** [comment]
```
- 50% firerate, keep dps same
- 10% range (tll -7%, becouse metal cost is x2, it has better dps but should have range bonus too)

tllflak increase buildtime 13995 -> 26435
```

**Comment by skymyj** [comment]
imho, too much dps but nix doesn't want decrease. So ok for me.

**Comment by nixtux** [comment]
Skymyj it's the same as the current dps and less than ba...

**Comment by skymyj** [comment]
ba : 
`			armflak_gun = {
				accuracy = 1000,
				areaofeffect = 192,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				canattackground = false,
				collidefriendly = false,
				craterareaofeffect = 192,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:FLASH3",
				gravityaffected = "true",
				impulseboost = 0,
				impulsefactor = 0,
				mygravity = 0.01,
				name = "FlakCannon",
				noselfdamage = true,
				predictboost = 1,
				range = 775,
				reloadtime = 0.55,
				soundhit = "flakhit",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.5,
				soundstart = "flakfire",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 2450,
				damage = {
					bombers = 250,
					commanders = 10,
					crawlingbombs = 10,
					default = 1000,
					fighters = 500,
					heavyunits = 10,
					mines = 10,
					nanos = 10,
					subs = 10,
					vtol = 250,
},`

So, it's 4xmore than ba. 454 dps in ba VS 2K in ta. With 775 range for ba vs +900 ta
It's not less or I missed something.

**Comment by skymyj** [comment]
Dont forget to rebalance other flak t3 Flak too.

**Comment by ksilversurfer** [comment]
```
- 73% firerate (arm and core 0.52s, tll 0.345s)
+ 8,3% damage for arm and core (600 + 8.3% = 650)
+ 17% damage fot tll (500 + 17% = 585)

arm core DPS = 1250
tll DPS = 1695

- 10% range (tll -7%, becouse metal cost is x2, it has better dps but should have range bonus too)

tllflak increase buildtime 13995 -> 26435
```

**Comment by ksilversurfer** [comment]
We should reduce energy cost...

**Comment by skymyj** [comment]
need to rebalance naval flak too..........

**Comment by ksilversurfer** [comment]
we need merge this then i can make pull request about cost

**Comment by ksilversurfer** [comment]
in other pr  naval flak

**Pull request merged**
