### PR TITLE
Balance armraven1.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Hmm i dont think increasing armshock1 hp is a good idea its so strong already v armraven , and then you also decrease ravens hp, why this seems so odd

**Comment by skymyj** [comment]
After testing. Shock is better vs catapult.
Decrease Hp and decrease damage / s

**Comment by ksilversurfer** [comment]
why not closer to BA values? (armraven.lua)

BA: 
burst =20
damage = {
		default = 450,
		subs = 5,
},

TA: 
burst =32
damage = {
                commanders =225
		default = 450,
		subs = 5,
},

my opinion for TA:

burst =26
damage = {
		default = 450,
		subs = 5,
},
why oh why commanders need to recieve less dmg here???
again its not commanders war... its units vs units
maxvelocity = 1.6 is ok now, also same is in BA

**Comment by nixtux** [comment]
@skymyj 
So 'After testing. Shock is better vs catapult.' 
Does this mean you didn't test before making these changes or after?

**Comment by skymyj** [comment]
For these balances, I watched games. Now, didnt test them in 'duel'

**Comment by skymyj** [comment]
For commanders damage,

**Comment by skymyj** [comment]
For commanders damage imho, all units with range >900 should have less damage.
The com is the king of this chess game. Ok to have normal damage in low range cause commanders are strong. But vs catapults how many times I saw a commandrrs destroyed? Too many

**Comment by skymyj** [comment]
For burst number, 26 or 32 is ok for me. With 940dmg per sec

**Comment by ksilversurfer** [comment]
I dont agree, commanders not suppose to be more resistant vs units than others,
I checked few units from BA and only strong laser from corkrog is limited to 1200dmg vs coms
and same for bantha lasor (1200dmg vs com)

Else weapons in corkrog or bantha deal same dmg for all ground units and vs coms

Example BA units that deal same dmg vs coms as vs units:
armshock or armraven
armraz same
corkarg same
shiva same
Juggernaut same

What is more: we have here stronger coms ! Battle, Assault etc... BA only one com.

**Comment by ksilversurfer** [comment]
> For burst number, 26 or 32 is ok for me. With 940dmg per sec

 - it dont need to be 900dmg/per sec
(26burst x 450dmg)/15sec = 780dmg/s

around 800 will be allright
but dont slow down unit, leave maxvelocity at 1.6

**Comment by ksilversurfer** [comment]
> After testing. Shock is better vs catapult.
> Decrease Hp and decrease damage / s

Shock has diffrent usage than catapult, its plasma weapon, slooow unit and allterrian.

**Comment by ksilversurfer** [comment]
I always thought that shock is worse than catapult :P

**Comment by skymyj** [comment]
yeah :) didn't know too until i tried

**Comment by ksilversurfer** [comment]
vote yes

**Pull request merged**
