### PR TITLE
Balance Flak

### PR DESCRIPTION
**Pull request by skymyj**
Mobile flak have 320dmg/s. 
Here we have 1K damage and more Aoe and Range.
Decrease Ratio E too high.

### CODE REVIEW

**Comment by skymyj** [comment]
If you are agree, i will change for naval and T3 Flak.

**Comment by ksilversurfer** [comment]
i like it !!! :)

**Comment by nixtux** [comment]
Players have been moaning about too big a nerf, going to have to revert it.

**Comment by skymyj** [comment]
I have no problem with that reverse. Experienced players will be happy.
Now, I will make 2 flaks and I will be safe on my techno land to lost 1 hour of my life to build my simcity. While this time, new players or players will low skills will make many fighters. They will spend so much resources to unstop my rapid bombers.

**Comment by skymyj** [comment]
Other solution is to decrease HP and/or speed from all bombers.

**Pull request merged**
