### PR TITLE
Add T4 Experimental Air Fortress

### PR DESCRIPTION
**Pull request by skymyj**
In work. Need to had, 3DO and BOS/COB Files

### CODE REVIEW

**Comment by skymyj** [comment]
#731 (you found the original icon in zip file)

**Comment by skymyj** [comment]
image

**Comment by nixtux** [comment]
Don't make it buildable ingame unless fully tested

**Comment by skymyj** [comment]
Totally tested and work

**Comment by nixtux** [comment]
I was referring to balance, needs testing don't make it buildable atm

**Comment by skymyj** [comment]
Oh ok.

**Comment by nixtux** [comment]
Also it should be built by a lab not con (with some sort of unlock),  way too op by con

**Comment by skymyj** [comment]
Maybe by the T4 Lab.

**Pull request merged**
