### PR TITLE
Balance armsiege and heavyimpact

### PR DESCRIPTION
**Pull request by skymyj**
Vs commanjd vehicle, need a boost. 
Cost 25% less, damage 1300 vs 1400 at same range and HP at 20K vs 52K.

### CODE REVIEW

**Comment by skymyj** [comment]
#328

**Comment by ksilversurfer** [comment]
I would not nerf armmcv.lua - becouse T3 Vehicles are still too weak. - vote n
Its good idea to boost armsiege.lua and heavyimpact.lua - vote y

**Comment by skymyj** [comment]
I can't edit. Don't understand why.
I'm ok to not change the armmcv but we have to increase HP for armsiege and heavyimpact by 1K.

**Comment by ksilversurfer** [comment]
> ..but we have to increase HP for armsiege and heavyimpact by 1K.
sure

**Comment by skymyj** [comment]
I don't have write access anymore. 
So Nixtux could make these changes.

**Comment by nixtux** [comment]
Just make a new pr with changes?

**Comment by skymyj** [comment]
#344

**Pull request closed without merging**
