### PR TITLE
Update abuilderlvl2.lua & cbuilderlvl2.lua

### PR DESCRIPTION
**Pull request by skymyj**
#275

### CODE REVIEW

**Comment by nixtux** [comment]
Don't forget we have tllbuilderlvl2 now.

**Comment by nixtux** [comment]
Have you finished here yet?

**Comment by skymyj** [comment]
yes

**Comment by nixtux** [comment]
This needs looking at https://github.com/techannihilation/TA/blob/master/units/tllbuilderlvl2.lua

Not balanced or buildable yet

**Pull request merged**
