### PR TITLE
Balance T3 Cons

### PR DESCRIPTION
**Pull request by skymyj**
ATM, we can't lock them with RC cause of TLL doesn't have RC.

I propose a little boost (+5%) in a first time and decrease buildpower.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
dont like idea here, we need find some other solution

**Comment by skymyj** [comment]
Other solution is to have T3 T4 metal extractor and a new AA fus.
But Nixtux doesn't like this idea : #675 

This balance was a solution to integrate the T3 cons. (they have no specials feature. So I would decrease timebuild for Kbot vs vehicle cons)

**Comment by ksilversurfer** [comment]
he not like reblancing of them
But i think he dont mind if we add new fusion and metal makers, but we need keep same ratio like is now

**Comment by skymyj** [comment]
Ok but we have to rebalance ratio for T3. ATM too high. And if we add a T4  Mex : 130M/S ?

**Comment by nixtux** [comment]
Nope closing arm/core should have a noticeable different in cost, this needs to stop

**Pull request closed without merging**
