### PR TITLE
Armpers (t3 Air gunship) : Add sprayangle = 1100

### PR DESCRIPTION
**Pull request by skymyj**
Projectiles are too much in line

### CODE REVIEW

**Comment by skymyj** [comment]
capture

**Comment by ZweisteinT** [comment]
Visual effect is cooler, but does it mean it does less damage cause of bullet spreading?

**Comment by skymyj** [comment]
Sure. You are right.
I think, there will be 10% lost. So we can increase by 10%

**Comment by ksilversurfer** [comment]
i would nerf them a bit, kinda op, its hard to send big units. If enemy has op air, you are ded.
Sending ground aa is pointless (well maybe if you have tons of ground aa)

**Comment by skymyj** [comment]
Ok. So do i decrease core gunship? And delete arm buff?

**Comment by ksilversurfer** [comment]
ye remove that buff, projectiles can be even less accurate (will make better visual effect)

**Comment by ksilversurfer** [comment]
and nerf core to be simillar to arm (balance)

**Comment by skymyj** [comment]
880 dmg / s for Core vs t3
960 (max)~864(10%lost) for arm vs t3

**Comment by ksilversurfer** [comment]
yhe values sounds promising

**Comment by nixtux** [comment]
y from me

**Pull request merged**
