### PR TITLE
Add T3 Vehicle Constructor

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
All tested and work. 
Balanced too vs Kbot.

**Comment by pcdummy** [comment]
Looks great.

**Comment by nixtux** [comment]
Show me the units please

**Comment by nixtux** [comment]
Also do you have the original OTA icons?

**Comment by nixtux** [comment]
Also script need fixing for 104+

**Comment by skymyj** [comment]
I can find the OTA icon

**Comment by skymyj** [comment]
[icon.zip](https://github.com/techannihilation/TA/files/1548883/icon.zip)
Sorry, didn't find the Core unit icon. I will search again.

**Comment by skymyj** [comment]
Video with units : https://1drv.ms/v/s!AgjKPxaKD1zLlHxIb3yMD-FAg8NW

**Comment by skymyj** [comment]
> Also script need fixing for 104+

Can you say me exactly what do we need ? Thanks

**Comment by skymyj** [comment]
Added Spice of Life. 
Just to be sure : 
ARM : Better range and less buildpower. Cost more E and less M. Have more velocity
Core : Better buildpower and less range. Have more HP.
TLL : Between ARM/CORE, cost more M.

**Comment by nixtux** [comment]
Closing all pr until labs are fixed

**Comment by nixtux** [comment]
These units look good btw

**Comment by nixtux** [comment]
Return values for script need fixing

**Comment by skymyj** [comment]
tllecv
armecv
Official Arm : 
[ARMECV.zip](https://github.com/techannihilation/TA/files/1603402/ARMECV.zip)

**Comment by skymyj** [comment]
corecv

**Comment by skymyj** [comment]
[TLLECV (initialy CORACD).zip](https://github.com/techannihilation/TA/files/1603414/TLLECV.initialy.CORACD.zip)

**Pull request merged**
