### PR TITLE
Balance coredauber.lua

### PR DESCRIPTION
**Pull request by skymyj**
Vs Sumo or Helldriver, they are under power.
They need a velocity boost.

### CODE REVIEW

**Comment by nixtux** [comment]
1. It looks bigger and heavier than helldiver ergo it should not have a faster velocity
2. They jump in stats is too much in one go 33% for velocity close to 50% for turnrate
3. Never just adjust turn rate with adjusting break rate and all the other needed values

**Comment by skymyj** [comment]
1. You are right.
2. & 3 Ok. Thanks. I will apply for nex times.

**Comment by skymyj** [comment]
So, I Increase maxdamage. Always < helldriver (max damage). Same velocity.

**Comment by ksilversurfer** [comment]
wont be too OP for its price?

**Comment by ksilversurfer** [comment]
hmm agree to boost HP, but +1000hp more can make it very strong for its cost

**Comment by ksilversurfer** [comment]
maybe lets make smaller change to 2820?

**Comment by skymyj** [comment]
Donee

**Pull request merged**
