### PR TITLE
Double Words

### PR DESCRIPTION
**Pull request by Antarac**
Change name of "Protector" into "Advocat" and all
T3 Anti-Nukes got their own unique Name so you can
delete "T3" in front of name to avoid double text.

I dont mind if the name is not "Advocat".
Only wanna delete double "T3".

### CODE REVIEW

**Comment by Antarac** [comment]
Ships miss the word "System".
Should i add System to them or delete System
for all other Anti-Nukes to make description shorter?

"Hive - Aircraft Carrier with Anti-Nuke"		Core T2 Ship
"Giant - Aircraft Carrier with Anti-Nuke"		TLL T2 Ship
"Colossus - Aircraft Carrier with Anti-Nuke"		Arm T2 Ship

**Comment by nixtux** [comment]
This PR broke with my mass featuredef work

**Comment by nixtux** [comment]
Just edit unitdef description/names and i will rebake featuredefs

**Comment by nixtux** [comment]
Please recheck with new unitdefs

**Comment by Antarac** [comment]
Im sorry but im not sure what you want me to do

**Comment by Antarac** [comment]
You said it's broken but i don't know what to do about it.
Should i close this and make a new pull request?

**Comment by nixtux** [comment]
Yeah please close and open a new pr based on latest techa

**Comment by Antarac** [comment]
Aye

**Pull request closed without merging**
