### PR TITLE
Update morph_defs_techa.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
A morph from a unit with a Missile to cannon weapon is strange

**Comment by skymyj** [comment]
you  are right

**Comment by skymyj** [comment]
Tarantula now

**Comment by nixtux** [comment]
0.05xp you sure?

**Comment by skymyj** [comment]
Sure. Cause, spider will not unbalance the party.
But I increase to 0.10.

**Comment by nixtux** [comment]
I was checking its was not a typo more than anything

**Pull request merged**
