### PR TITLE
Optimize unit_add_impulse, add to other riot like units

### PR DESCRIPTION
**Pull request by sqrtone**
It add impulse BOOST to units:
Arm Liche,
Arm Fatboy and upg Fatboy
Core Golliath and upg Golliath
Core Demolisher
Core Metron
Arm Kronos

### CODE REVIEW

**Comment by sqrtone** [comment]
Tested, works, and feels balanced.

**Comment by skymyj** [comment]
It misses many units/weapons. 
- tllblind, tllcolossus, tllthump... 
- All weapons using goliath weapn (talon_fdog, Shiva, armtigre2.......)

**Comment by sqrtone** [comment]
ok i will add

**Comment by sqrtone** [comment]
done, rest units we can add after some games - im not sure what units we miss

**Comment by sqrtone** [comment]
can you merge pls? :)

**Pull request merged**
