### PR TITLE
Metal Maker TLL Balance

### PR DESCRIPTION
**Pull request by skymyj**
- see the armmmkr (T2 Arm MM) /  42930E + 1009M + 40000 Time. Tranform 800E. (1.6M for 100E)
- see the tllammaker (T2 TLL MM) / 8000E + 1150M + 35000 TIME. Transform 1000E (1.4M for 100E). HP = 800
- see the coramaker (T1.5 CORE MM) / 6000E + 188M + 4400 TIME. tranform 256 (1.4M for 100E)

### CODE REVIEW

**Comment by skymyj** [comment]
Arm / Core T2 Metla Make r(underwater) are too high cost.

**Comment by skymyj** [comment]
To resume. 
Increase Energy Cost for T2 Metal Maker to balance with Arm / Core.
Decrease MEtal Cost for Arm / COre Underwater Metal Maker to blance with TLL.

**Comment by pcdummy** [comment]
Good.

**Comment by nixtux** [comment]
Update version.txt please

**Pull request merged**
