### PR TITLE
Proposal for T4.5 Balance

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Atm only exoarm is ready for balance all other units still need work, only 1 of fatshrew weapons work. Please hold off on fatshrew for now.

**Comment by skymyj** [comment]
Imho, the 4.5 is no sense for me. 
The X.5, is for T1 T2 T3, unit from lab unlocked by Tech Center. 

I think a lot, and the best we could do is to lock the Lab with T3 RC. 1 or 2 units could be made and other unlocked by T4 RC

**Comment by skymyj** [comment]
Atm only exoarm is ready for balance all other units still need work, only 1 of fatshrew weapons work. Please hold off on fatshrew for now. 
=> I begin to balance it. I know there is a lot of to do. I dodn't see the weapon on this unit yet.
We need a Big Flammer turtoise too (like mario kart)

**Comment by nixtux** [comment]
OK time to reopen there sizes are now fixed and there all all here apart from tll (Still working on this)

**Comment by nixtux** [comment]
Add tll lab + con now

**Pull request closed without merging**
