### PR TITLE
Update corprot.lua

### PR DESCRIPTION
**Pull request by skymyj**
Velocity for arm : 1.25
sightdistance : 455

I think, les for corprot cause more range and damage.
Actually, they are too quick.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
hmm reducing speed?

**Comment by ksilversurfer** [comment]
well i would compare cost/dmg to arm sniper

**Comment by ksilversurfer** [comment]
speed reduce is not always funny

**Comment by skymyj** [comment]
A key to have a good balance in this game is : 
- More range/HP/damage a unit have and more slow should be (at same cost)

**Comment by skymyj** [comment]
Just decrease range.

**Comment by ksilversurfer** [comment]
agree

**Pull request merged**
