### PR TITLE
Add new model for Vengence

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Does he wobble when he walks?

**Comment by skymyj** [comment]
Yes I think.

**Comment by skymyj** [comment]
He should with : 
turn pelvis to y-axis <4.000000> speed <12.000000>;
turn pelvis to x-axis <6.000000> speed <6.000000>;

**Comment by nixtux** [comment]
Any chance of a video of him in action?

**Comment by skymyj** [comment]
Sure

**Comment by skymyj** [comment]
https://1drv.ms/v/s!AgjKPxaKD1zLlwZxYGzrFFclYK6B

**Comment by ksilversurfer** [comment]
looks good

**Comment by nixtux** [comment]
Imo there was nothing wrong with the old model, i will merge

**Pull request merged**
