### PR TITLE
Add new rocket for ARM T4

### PR DESCRIPTION
**Pull request by skymyj**
ATM, too little and effect in middle from rocket.
Now we have a rocket to the team color  and model increased : 
image

### CODE REVIEW

**Comment by skymyj** [comment]
Add correction for normal rocket too : 
image

**Comment by skymyj** [comment]
image

**Comment by ksilversurfer** [comment]
yeah looks ok

**Comment by nixtux** [comment]
Effect in middle of rocket is an easy fix btw

**Pull request merged**
