### PR TITLE
Rebalance Speed & Hp for com

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Ok, we have to rebalance com Power. 

ARM/Core : (for each level : +2.5KHP and +0.1 speed)

T1 2.5K HP 1.2 Speed
Eco 2.5K HP 1.2 Speed
Battle 5K HP 1.3 Speed
Assault 7.5K HP 1.4 Speed
Star 10K HP 1.5 Speed
Supreme 12.5K HP 1.6 Speed

TLL : (for each level : +2.5KHP and +0.1 speed)

T1 5K HP 1.1 Speed
Eco 5K HP 1.1 Speed
Battle 7.5K HP 1.2 Speed
Assault 10 HP 1.3 Speed
Star 12.5K HP 1.4 Speed
Supreme 15K HP 1.5 Speed

**Comment by nixtux** [comment]
Reason?

**Comment by skymyj** [comment]
Actually Commanders are really too strong. 
On small map, a battle com is unblockable. 
On large map, an assault com good played, can stop too many T3.5 T4 units

**Comment by skymyj** [comment]
With Speed decrease, they are more easy to kill

**Comment by nixtux** [comment]
Why are you raising tll com speed, I disagree with that change they need to be slower due to the fact there lightingcannon weapon deals full damage whatever the range.

**Comment by skymyj** [comment]
Well... TLL are slower than ARM/COre and than before ❌

**Comment by nixtux** [comment]
Sorry misread what you initially said.

**Comment by ksilversurfer** [comment]
so... after change Tll T1 Com will be 10% (was 13%) slower than Core/Arm 
and Core/Arm Com will be HP nerfed by 500HP ?

arm/core 2500HP vs Tll 4500HP (was 3000 vs 4500) t1 lvl
arm/core ~3% speed nerf on T1 lvl

**Comment by ksilversurfer** [comment]
Idea of balancing coms is nice skymyj,
but dont make TLL more op than is now (com)

**Comment by skymyj** [comment]
Actually it s tll com that have be a massive nerf with speed for assault star and supreme.

**Comment by ksilversurfer** [comment]
massive?

**Comment by ksilversurfer** [comment]
pls balance it fair

**Comment by ksilversurfer** [comment]
my actuall tactic: i abuse op units and i try balance them

since now: juno in test version is perfect, and transports with crawlings is fixed.
horgue  need to be more precise (much more) and should has faster move speed

Tomorrow i will make new pull requests

**Comment by skymyj** [comment]
Change done.
-500 HP for each TLL Com.

On a futur release, I will clean up the damage / S and range for weapon.
(actually too much damage vs air with classic laser/lighting)

**Comment by ksilversurfer** [comment]
ok its now ok, at least same balance as before arm/core vs tll
but honestly range of lighting should be the same as arm/core lasor
now is 330, nerf tll to 300.

Tll still will have big advantage becouse lighting deal 100% dmg at full range.

**Comment by skymyj** [comment]
ARM/CORE commander are better vs span Unit. (0.4 reload and more damage / s reduced with distance)
Lighting inflicts full damage. 
I think these caracteritics are balanced together. 
Now, we have to reduce tll range.

**Comment by skymyj** [comment]
Please, need vote to merge this. 
After we will do weapon.

**Comment by ksilversurfer** [comment]
agree here

**Comment by ZweisteinT** [comment]
but if you decrease core/arm from 3000 to 2500... 
and tll from 4500 to 4000...

Then tll will be 1.6 times heavier, while previously tll was 1.5 times heavier.

**Comment by skymyj** [comment]
I'm ok with you zweis, but the fact is : ARM / CORE (assault, star and supreme) was unbalanced from start. 

ARM/CORE Com had less HP at Standar, Eco and Battle than TLL.
At Assault, Star and Supreme, they had same HP than TLL :=)

**Comment by ZweisteinT** [comment]
yeah, at higher levels those little 2.5k differences may not be so important. but i think at t1 level it may be.

**Comment by nixtux** [comment]
All commanders should have the same hp per level, atm with tll having an advantage it make this gadget pointless https://github.com/techannihilation/TA/blob/master/luarules/gadgets/mo_preventcombomb.lua

**Comment by nixtux** [comment]
Ergo if that gadget is pointless not bother playing any 1v1 games against tll.

**Comment by skymyj** [comment]
I'm ok to have same hp. It's just on the ta history to have tll less speed and more hp.

**Comment by skymyj** [comment]
So i will change to have same stats. And fix the range on laser for each commander type

**Comment by nixtux** [comment]
Iirc its just tll lighting range which needs reducing in line with arm/core

**Comment by skymyj** [comment]
Done. 
All commander have same HP, Speed and range for primary weapon.

**Pull request merged**
