### PR TITLE
Update airwolf3g.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by Antarac** [comment]
I would comment but dunno what this is.

**Comment by skymyj** [comment]
T3 air fighter arm

**Comment by Antarac** [comment]
I know the unit but whats this change?

**Comment by skymyj** [comment]
If you see, icon appear in red font.
This change will change font color in blue.

**Comment by nixtux** [comment]
That's sort of correct I will still need to generate new icon in another commit

**Comment by skymyj** [comment]
Nix, can we merge it ?

**Comment by nixtux** [comment]
Not yet, I will merge it when I can generate unitpic otherwise I may forget

**Comment by Antarac** [comment]
Thanks, i wondered a while already how that works with icon unit color.

**Pull request merged**
