### PR TITLE
Balance Timebuild for some T3 units

### PR DESCRIPTION
**Pull request by skymyj**
No sense for timebuild

### CODE REVIEW

**Comment by nixtux** [comment]
Why an increase in buildtime of x2.5 its a massive jump in one go imo

**Comment by skymyj** [comment]
Indeed. To comparaison, Karg is to 50000+. 
40000 is always short time for T3 unit.

**Comment by ksilversurfer** [comment]
maybe up to 30k, shiva is not often used in games

**Comment by skymyj** [comment]
I propose 35K like Tesla Tank for TLL.

**Comment by ksilversurfer** [comment]
ye ok

**Comment by skymyj** [comment]
Same for champion. A 5.8KM can't have 25K timebuild

**Pull request merged**
