### PR TITLE
Add explosiongenerators

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Won't work for armmcv or cormcv unless you update scripts with emit-sfx, can't merge until then

**Comment by skymyj** [comment]
Yes I know. This commit will contains many units. And sure for script. Yesterday I bugged many hours on a new unit 
Not finished yet for bos cob.

**Comment by nixtux** [comment]
K, let me know when your finished I will merge, also do you want this effect made smaller?

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
We could add armbull2

**Comment by skymyj** [comment]
Done. 
Conflicts but it's ok. 
Need manually  merge from admin here

**Comment by skymyj** [comment]
We need You Nix to iverpass this conflicts. All work with tests

**Pull request merged**
