### PR TITLE
Infiltrator : Change weapon model (nd rebalance a little)

### PR DESCRIPTION
**Pull request by skymyj**
Actually, after shooting, a Socket of a ball fly. 
So ammunition can't be laser but bullet !

Weapon from maverick. +/- same balance.

### CODE REVIEW

**Comment by nixtux** [comment]
What please explain more clearly please. Are you saying a bullet shell is shown after the units fires? If so the other option is remove the bullet from the animation script.

**Comment by skymyj** [comment]
re you saying a bullet shell is shown after the units fires? => yes.
I think it's more easy like this. 
Moreover, the weapon looks like a gun.

**Comment by nixtux** [comment]
Ok I'm fine with this change.

**Comment by ksilversurfer** [comment]
ok im fine too

**Pull request merged**
