### PR TITLE
Add Arm ultimate fusion

### PR DESCRIPTION
**Pull request by skymyj**
image

### CODE REVIEW

**Comment by nixtux** [comment]
Looks fugly

**Comment by skymyj** [comment]
Better render in play : 
image

**Comment by nixtux** [comment]
No still fugly

**Comment by skymyj** [comment]
This looks better imo : 
image

**Comment by nixtux** [comment]
No that's even worse

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
image

**Comment by ksilversurfer** [comment]
i think that Arm dont need better fusion, 
lets leave to CORE to have largest one only.

**Pull request closed without merging**
