### PR TITLE
Balance Metal production from MM

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Reason ?

**Comment by skymyj** [comment]
The reason is twice : 
- First, rebalance the difference ratio between TLL and ARM/CORE.
- Decrease Metal production from Fusion Farm. We need to push player to play more battle, than just simcity. In this way, it will always better to collect E than go battle, but it's more balanced imho.

**Comment by skymyj** [comment]
This commit is to prepare another too : 
- The MM integrated for all TLL Fusion. We have to stop to generate metal production from fusion. Cause, they can't use efficiently energy weapon like DMC or Hydre.

**Comment by ksilversurfer** [comment]
i think this is very good idea, now ppl only doing simcity, nerfed mm ratio should force players to
fight more.

**Comment by lll8D** [comment]
You can just add manual on/off button for metalmaking in tll fusions. Or make it automaticlay like the simple mms do? I agree with reachign t3/t4 too fast but i rly hope it wont effect the t2 base size :D if people will have to build too much t2 eco it migth be a problem to reclaim it/find a free space for t3/4

**Comment by nixtux** [comment]
Atm MM all have some sort of on/off visual, how will a player know if a fusion is producing metal?

**Comment by skymyj** [comment]
Same than arm driller. 
We just could add a piece that give information

**Comment by skymyj** [comment]
I propose to delete all metal production and no add MM for TLL.
This faction will have less ratio than arm/core/talon. Cause units ost more metal than E. 
So just delete all metal production imho

**Pull request merged**
