### PR TITLE
Add new system t4/t5

### PR DESCRIPTION
**Pull request by skymyj**
To work, need to merge : https://github.com/techannihilation/TA/pull/1352
#1291

### CODE REVIEW

**Comment by ksilversurfer** [comment]
use this for now:
```
		buildoptions = {
			[1] = "tllmarmelade",
			[2] = "irritator",
			[3] = "tllhailstorm",
			[4] = "hyperion",
			[5] = "tllgorgon",
			[6] = "tllmcv",
			[7] = "tllcolossus",
		},
```
tllsauron was not ready

**Comment by ksilversurfer** [comment]
ok what is the point of rebelancing T4 constructors?? please explain

**Comment by skymyj** [comment]
Well, all rc cons tx cost more than cons tx.
Its to keep this balance. And increase cost due these cons can buid t4 unit wirhout lab.
And can make the final weapon. So increase cost will just retarded tsar construction.

**Comment by ksilversurfer** [comment]
ah ok

**Comment by ksilversurfer** [comment]
abuilderlvl5.lua metal cost not match mass

**Pull request merged**
