### PR TITLE
Battle COM

### PR DESCRIPTION
**Pull request by skymyj**
#1280 
With this, players will play more Battle Com.

### CODE REVIEW

**Comment by Antarac** [comment]
How about you explain changes in code and not just add the changes?
You know what you do and you could explain it once.
More easy than every single person need to read code.

**Comment by skymyj** [comment]
These 2 delete lines explain, no need anymore to make RC to unlock them.
Goal is to choose Battle Com, and Make these T1.5 Cons for Eco too. 
The big differnce between Eco / Battle com, is the outpout resources. 
Eco could make eco building faster.
Battle can rush in front.

**Comment by ksilversurfer** [comment]
this idea make no sens to me, i vote to remove t1.5 con from RC, so battle com will be more usefull

**Comment by skymyj** [comment]
Atm tll have this system and there is no abuse or op. It just will increase battle com imho.
Why not to delete builder from rc.

**Comment by skymyj** [comment]
I propose to merge it. If op we could revert it. 
Maybr take suggestion from keij

**Comment by ksilversurfer** [comment]
OK LETS TEST

**Pull request merged**
