### PR TITLE
Balance armflash and corgator

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Vs armflash : 
- More Hp +200
- Damage x 2
- Same speed

**Comment by ksilversurfer** [comment]
**topic: Balance armflash1**
why then changing aslo values for armflash???

Too much nerf for armflsh1, and you increased cost a bit also...

**Comment by ksilversurfer** [comment]
also armflash1 has description:  Very Fast Assault Tank
you nerfing to same speed as armflash - i totally not agree

**Comment by skymyj** [comment]
3 armflash 1 kill easely a commander

**Comment by skymyj** [comment]
So, we can keep same HP and increase HP.
Daamge have been increased

**Comment by nixtux** [comment]
Don't reduce speed for fuck sake, balance another way

**Comment by nixtux** [comment]
Do these really need balancing they have been like this for long time, what the reason behind the wanted change?

**Comment by nixtux** [comment]
This is some nerf hp reduced by around 40%, buildtime increased by shroud 30%, and nearly 25% increase in energy cost, seems way too much imo

**Comment by ksilversurfer** [comment]
too much hp nerf: maybe lets make something 50/50 old vs new value
hp for armflash1: 700
leave build time as was 2000
energy cost: 1700

should be fair

**Comment by Antarac** [comment]
You refer to the last game where ruggis comm got killed by your flash?
It was 10 flash, so worth more than 1000 metal,
against a unmorphed and damaged commander with 69% health.
Commander didnt use dgun against the flashs that were on big bunch.
http://replays.springrts.com/replay/77b826595389c622c6eeaa789e82388f/
At minute ~19 you can see it.

**Comment by skymyj** [comment]
No I refer to 2 previous game. Keiji comes with 3 flashs

**Comment by nixtux** [comment]
At what time ingame does this happen? And where?

**Comment by nixtux** [comment]
Won't merge, I'm not going to merge any requests with rounding of t1 units, imo with such low costs rounding really effects stats, closing issue, reopen when rounding is removed.

**Comment by Antarac** [comment]
It was 3 flash tanks, 2 agile flash tanks and 2 samson missile tanks worth 838 metal.
It took 13 seconds from first to last shot to kill unmorphed commander.
Commander didnt use dgun and he might taken little damage from exploding units around him.
http://replays.springrts.com/replay/b3b226599bbb77206ada6780383cff95/
Nixtux, at 6:13 skymyj's Commander gets the first hit.

**Comment by skymyj** [comment]
you are right antarac.

**Pull request closed without merging**
