### PR TITLE
Balance StarBurst Launcher for T3.5 Units

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
700 damage is very high. (vs commander and structures like Geo, metal maker...)
So reduced by 2 for Krog and ArmOrco will be good. (350). With 5% decrease resources for them.
Arm Furie fixed at 500. Same reload but rocket fixed at 500 dmg for each.

**Comment by ksilversurfer** [comment]
dont agree, then it will be much easier to kill them by coms... 
we play Coms Vs T3.5 ?

I thought we play T3.5 vs T3.5

Dguning large units only happen in extreme situations.

**Comment by skymyj** [comment]
700 is too high. what about 500 ? 
Commanders have been nerfed. Less speed & HP.

**Comment by skymyj** [comment]
Now we have : 

All weapon damage vs commander divide by 2 except StarBurst Launcher fixed at 500 damage / s.

**Comment by skymyj** [comment]
Before we had starbust launcher at 350dmg/s vs commander. And some blue beam at 20% damage vs com

**Comment by ksilversurfer** [comment]
Agree now

**Comment by skymyj** [comment]
Time to merge it :)

**Comment by ksilversurfer** [comment]
Vote Yes

**Pull request merged**
