### PR TITLE
Delete Explosion, Add sonar, increase weapon velocity => turtle anti sub

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
+ correction for Hover anti Sub. 
(bug : 1800 sonat for core Anti Sub :X)

**Comment by nixtux** [comment]
Skymyj. 

> This branch has conflicts that must be resolved

**Comment by nixtux** [comment]
skymyj This branch has conflicts that must be resolved

**Comment by skymyj** [comment]
resolved :)

**Pull request merged**
