### PR TITLE
Add T3 Air Cons

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Need pic of each con

**Comment by skymyj** [comment]
[icon.zip](https://github.com/techannihilation/TA/files/1603380/icon.zip)

**Comment by skymyj** [comment]
For TLL, it's the same than tllaca. Maybe you can increase size of airplane

**Comment by nixtux** [comment]
Coreca looks like an attack ship rather than some sort of constructor

**Comment by skymyj** [comment]
There is no weapon visible on it. 
I think it's a good idea. And if you find better, we could change model in the future.

**Comment by nixtux** [comment]
Merging but we must replace core will a better model

**Comment by nixtux** [comment]
Texture are missing from core

**Pull request merged**
