### PR TITLE
Add Floating LLT

### PR DESCRIPTION
**Pull request by skymyj**
Icons : 
armfllt
corfllt

### CODE REVIEW

**Comment by skymyj** [comment]
Added for all com v0 v1 Fusion and Battle
Added for all construction ship and hover t1

**Comment by skymyj** [comment]
image

**Comment by nixtux** [comment]
Tll floating units rock on water, this one does not

**Comment by skymyj** [comment]
Done

**Comment by nixtux** [comment]
Nope not, check https://github.com/techannihilation/TA/commit/bfe473d76c260d7697169230fda0c09ea4ae8171#diff-33a8c78d687eead6e2f53a35e363e116

**Comment by skymyj** [comment]
Done

**Pull request merged**
