### PR TITLE
Add armhope t5

### PR DESCRIPTION
**Pull request by skymyj**
Tested and work.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
oh c'mon 2000 rocket range with that price?
It can fly can fire rockets up to 2000 range.... its op omg...

**Comment by skymyj** [comment]
Mds will be more used. 
How much range dobyou rhink better? 1600?

**Comment by ksilversurfer** [comment]
1500 max for any unit...
exception are units like corhowie, but they are slow and they not fly, and they are low hp compared to
T4/T5 units.

If you make T4/T5 unit with such big range then whole game make no sense!

**Comment by ksilversurfer** [comment]
Or we will need bigger maps.... :/ This is not good

**Comment by ksilversurfer** [comment]
ok need wait for Nixtux to comment

**Pull request merged**
