### PR TITLE
Update exoarm.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Plasma Shield  missing

**Comment by nixtux** [comment]
I don't see the revert needed to to old weapons, I will push changes myself, just rebalance damage

**Comment by skymyj** [comment]
Please, don't revert the lighting weapon. It's uglly and no sense. 
It's a plasma gun.

**Comment by skymyj** [comment]
we can decrease burst or size if too much cost in particules

**Comment by nixtux** [comment]
Wait for me to push my changes then make new PR of balance only

**Pull request closed without merging**
