### PR TITLE
Delete special Damage vs Commander

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
agree ! :) vote yes

**Comment by nixtux** [comment]
Why?

**Comment by ksilversurfer** [comment]
imo commanders should't have special privileges, also we have way stronger commanders than in BA
or if nix dont want to delete special damage vs commanders, lets make it 66% of default damage.

**Comment by ksilversurfer** [comment]
50% is way too much

**Comment by nixtux** [comment]
Just wanted to know the reason behind the change, do we want it removed from all units?

**Comment by ksilversurfer** [comment]
i think from most of units, but for some fast ones like razorback and t4 razorback we should keep special damage vs commanders

**Comment by ksilversurfer** [comment]
reference: https://github.com/techannihilation/TA/pull/223

**Pull request closed without merging**
