### PR TITLE
Rebalance tllhailstorm and increase Scale

### PR DESCRIPTION
**Pull request by skymyj**
Scale *1.85

### CODE REVIEW

**Comment by ksilversurfer** [comment]
You just copy pasted what i showed you, 
those values collisionvolumescales = "200 310 170", are tooooo BIG !!!

Anyway tllhailstorm aslo dont need elipsoid hit box, spherical is ok.
So you cane remove that lines:

+		collisionvolumeoffsets = "0 -5 -3",
 +		collisionvolumetest = 1,
 +		collisionvolumescales = "200 310 170",
 +		collisionvolumetype = "Ell",

**Comment by ksilversurfer** [comment]
you almost doubled hailstorm weapon speed, it will look ugly, way too fast.
Leave it at 630.

**Comment by ksilversurfer** [comment]
just remove that lines, all rest is ok, I tested AND leave weapon speede at 630 pls.

**Comment by ksilversurfer** [comment]
ahh and i need update footprint

**Comment by skymyj** [comment]
Done. Footprint at 5 ?

**Comment by ksilversurfer** [comment]
how i can explain? footprint size is when you seletct unit green rectangle

**Comment by skymyj** [comment]
Ok :)

**Comment by skymyj** [comment]
Done

**Comment by skymyj** [comment]
Add footprint at 7 with Nix suggestion

**Comment by skymyj** [comment]
Annd add good movment class

**Comment by skymyj** [comment]
Should work with printfoot 7 and new mvt class

**Comment by ksilversurfer** [comment]
adding new moveclass? - no
So?
Rescale it to footprint 9
Would be * 1.3 - from this
Agree all :P?

**Comment by skymyj** [comment]
Best is to footprint at 9 imho

**Comment by ksilversurfer** [comment]
but model scale too ofc

**Comment by skymyj** [comment]
ok. We should scale lab too

**Comment by ksilversurfer** [comment]
ok please do

**Comment by nixtux** [comment]
Don't add new movedef ffs

**Comment by skymyj** [comment]
I tested again. 
Legs move very quick.
There are so many parameters to scale in walklegs function. 
Do you have tips ?

**Comment by skymyj** [comment]
Weapon can't pass the 2000 range. 
Range with balance is at 3000.

Is it script or other config to change ?

**Pull request closed without merging**
