### PR TITLE
Update akmech.lua

### PR DESCRIPTION
**Pull request by skymyj**
Revert Metal Cost. Keep energy cost.
Change damage for weapon but same balance.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
Skymyj akmech is strong just need energy for laser shot.
And for some reason laser not shooting when you move unit back.
I need to check why.

**Comment by skymyj** [comment]
Indeed. I already checked the bug with laser whle moving.

**Comment by skymyj** [comment]
Add 600 energy storage. Maybe it will resolve problem

**Comment by ksilversurfer** [comment]
it is not storage issue

**Comment by ksilversurfer** [comment]
pls wait with it i will fix soon :D

**Comment by ksilversurfer** [comment]
This still need fix, at moment this unit is not soo bad balanced.

**Pull request closed without merging**
