### PR TITLE
Change akmech Model

### PR DESCRIPTION
**Pull request by skymyj**
Add missile instead plasma.
#1329

### CODE REVIEW

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
We could add a blue shield too. 
Atm, i have not add this feature.

**Comment by nixtux** [comment]
IMO original model looked better

**Comment by ksilversurfer** [comment]
Killfree asked to revert to old old AK-X1, i think its good idea. I actually dislike new model

**Comment by skymyj** [comment]
Ok for me. Please revert.

**Comment by ksilversurfer** [comment]
done
https://github.com/techannihilation/TA/commit/8aadd6440b877ced39bb8314e10d379635c9fbca

**Pull request closed without merging**
