### PR TITLE
Nerf Grim Reaper

### PR DESCRIPTION
**Pull request by ksilversurfer**
Pls comment, and suggest other values if i'm nerfing it too much.
Grim Reaper is too OP

### CODE REVIEW

**Comment by ksilversurfer** [comment]
or leave it as was, but nerf range?

**Comment by skymyj** [comment]
Cost very high. 
I think we should test together vs arm furie and krogoth.

**Comment by skymyj** [comment]
TLL have no t3.5 unit. So, if he need balance, only cost I think

**Comment by ksilversurfer** [comment]
check now

**Comment by skymyj** [comment]
Did you test ? 950 Range is too low for a sniper at 27kM. 
Add 4 sniper vs 1 furie with this config and they all die.

**Pull request closed without merging**
