### PR TITLE
Change model tllasgard.lua and rebalance weapon

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Reason?

**Comment by skymyj** [comment]
Fixed bug like angle turret.
Ratio M/E TLL.
Spice of life : TLL less damage but more AOE.
For Arty ship : Decrease damage from secondary weapon. (same power than bats weapon).
Add good flare in 3do model.

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA/pull/1378

**Comment by nixtux** [comment]
You rounded costs, just that change means it's a no from me atm

**Comment by skymyj** [comment]
Changed

**Pull request merged**
