### PR TITLE
Icon TLL Veh & Kbot T2

### PR DESCRIPTION
**Pull request by skymyj**
Signed-off-by: skymyj <skymyj@hotmail.com>

### CODE REVIEW

**Comment by skymyj** [comment]
Add sharpened filter

**Comment by nixtux** [comment]
unitpics/tllamphibot.png should have water as the background like original.

**Comment by skymyj** [comment]
Ok. I will do.

**Comment by skymyj** [comment]
About quality ? Is it ok for you ?

**Comment by pcdummy** [comment]
Merge?

**Comment by skymyj** [comment]
I d like have a response. 
We could finish all this work since long time if I had a response. 

Thanks.

**Comment by pcdummy** [comment]
We have 2 votes for merge, not sure what you need sky.

**Comment by skymyj** [comment]
I'm waiting for Nix agree. 
I want to have same result than Icon from Nix

**Comment by skymyj** [comment]
Nix ? Are you here ?

**Comment by nixtux** [comment]
Wont merge until this is in its own PR https://github.com/techannihilation/TA/pull/10/commits/3364c48d8c0759b4ae7894dc2a886e864b243548

**Comment by skymyj** [comment]
OK. I close and repost the good items.

**Pull request closed without merging**
