### PR TITLE
Add new model tlldmc

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Whats new about it?

**Comment by skymyj** [comment]
Nothing. I don't understand : they are moved in main directory. 
I should have a bug with my commands. I will check that.
So I delete them and replace in 3do directory. 
You will have less work like this instead of revert all.

**Comment by skymyj** [comment]
We have a bug with the ArmorDef I think : 
Using writeable configuration source: "C:\Users\skymy\Documents\My Games\Spring\springsettings.cfg"
Available log sections: ModelRenderContainer, DecalsDrawerGL4, Path, AutohostInterface, Sound, BumpWater, GameServer, Net, LuaSocket, RoamMeshDrawer, CregSerializer, DynWater, SkyBox, Texture, Font, Shader, KeyBindings, ArchiveScanner, FarTextureHandler, Piece, CSMFGroundTextures, GroundMoveType, Model, OBJParser, VFS
Enabled log sections: Sound(Notice)
Enable or disable log sections using the LogSections configuration key
  or the SPRING_LOG_SECTIONS environment variable (both comma separated).
  Use "none" to disable the default log sections.
LogOutput initialized.
============== <User Config> ==============
  AdvSky = 1
  AllowDeferredMapRendering = 1
  AllowDeferredModelRendering = 1
  GroundDetail = 53
  GuiOpacity = 0.3
  HardwareCursor = 1
  InputTextGeo = 0.26 0.73 0.02 0.028
  LastSelectedMap = Small Supreme Battlefield V2
  LastSelectedMod = Tech Annihilation $VERSION
  LastSelectedScript = Player vs. AI: KAIK 0.13
  MaxDynamicMapLights = 4
  MaxDynamicModelLights = 4
  MaxParticles = 12000
  ScreenshotCounter = 11
  ShadowMapSize = 2047
  Shadows = 1
  ShowFPS = 1
  ShowSpeed = 1
  UnitIconDist = 412
  Water = 0
  snd_volmaster = 18
============== </User Config> ==============
============== <User System> ==============
  Spring 104.0
    Build Environment: boost-105500, GNU libstdc++ version 20130531
     Compiler Version: gcc-4.8.1
     Operating System: Microsoft Windows
Microsoft Home Premium Edition, 64-bit (build 9200)
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz; 8121MB RAM, 10297MB pagefile
     Binary Word Size: 32-bit emulated
     Deque Chunk Size: 128
        Process Clock: std::chrono::high_resolution_clock
   Physical CPU Cores: 4
    Logical CPU Cores: 4
============== </User System> ==============
[good_fpu_init] CPU SSE mask: 127, flags:
	SSE 1.0:  1,  SSE 2.0:  1
	SSE 3.0:  1, SSSE 3.0:  1
	SSE 4.1:  1,  SSE 4.2:  1
	SSE 4.0A: 0,  SSE 5.0A: 0
	using streflop SSE FP-math mode, CPU supports SSE instructions
[WatchDogInstall] Installed (HangTimeout: 10sec)
[WatchDog::RegisterThread] registering controls for thread [main]
[GL::CheckAvailableVideoModes] desktop={1920x1080x24bpp@60Hz} current={1920x1080x24bpp@60Hz}
	display=1 modes=45 bounds={x=0, y=0, w=1920, h=1080}
		[ 1] 1920x1080x24bpp@60Hz
		[10] 1680x1050x24bpp@60Hz
		[13] 1600x1024x24bpp@60Hz
		[15] 1600x900x24bpp@60Hz
		[17] 1440x900x24bpp@60Hz
		[23] 1280x800x24bpp@60Hz
		[25] 1280x720x24bpp@60Hz
	display=2 modes=45 bounds={x=1920, y=0, w=1920, h=1080}
		[ 1] 1920x1080x24bpp@60Hz
		[10] 1680x1050x24bpp@60Hz
		[13] 1600x1024x24bpp@60Hz
		[15] 1600x900x24bpp@60Hz
		[17] 1440x900x24bpp@60Hz
		[23] 1280x800x24bpp@60Hz
		[25] 1280x720x24bpp@60Hz
[GR::CreateSDLWindow] using 0x anti-aliasing and 24-bit depth-buffer (PF="SDL_PIXELFORMAT_RGB888")
[GR::LogVersionInfo]
	SDL version : 2.0.4 (linked) / 2.0.4 (compiled)
	GL version  : 4.5.0 NVIDIA 385.69
	GL vendor   : NVIDIA Corporation
	GL renderer : GeForce GTX 970/PCIe/SSE2
	GLSL version: 4.50 NVIDIA
	GLEW version: 1.5.8
	GPU memory  : 4096MB (total) / 3327MB (available)
	SDL swap-int: 1
	
	ARB shader support        : 1
	GLSL shader support       : 1
	FBO extension support     : 1
	NVX GPU mem-info support  : 1
	ATI GPU mem-info support  : 0
	NPOT-texture support      : 1 (1)
	texture query-LOD support : 1 (1)
	24-bit Z-buffer support   : 1 (-)
	primitive-restart support : 1 (1)
	clip-space control support: 0 (0)
	frag-depth layout support : 1 (-)
	
	max. FBO samples             : 32
	max. texture size            : 16384
	max. texture anisotropy level: 16.000000
	max. vec4 varyings/attributes: 31/16
	max. draw-buffers            : 8
	max. rec. indices/vertices   : 1048576/1048576
	max. uniform buffer-bindings : 84
	max. uniform block-size      : 64KB
	
	enable ATI-hacks : 0
	compress MIP-maps: 0
[GR::ToggleGLDebugOutput] OpenGL debug-context not installed (dbgErrors=0 dbgTraces=0)
[VSync::SetInterval] interval=0 (disabled)
[GR::LogDisplayMode] display-mode set to 1920x1080x24bpp@60Hz (fullscreen::decorated)
Using read-write data directory: C:\Users\skymy\Documents\My Games\Spring\
Using read-only data directory: C:\Users\skymy\Documents\My Games\Spring\engine\104.0\
Scanning: C:\Users\skymy\Documents\My Games\Spring\engine\104.0\base
Scanning: C:\Users\skymy\Documents\My Games\Spring\maps
Scanning: C:\Users\skymy\Documents\My Games\Spring\games
Scanning: C:\Users\skymy\Documents\My Games\Spring\packages
[~ScopedOnceTimer][CArchiveScanner::ScanAllDirs] 1549ms
[ThreadPool::SetThreadCount][1] wanted=3 current=1 maximum=4 (init=1)
[ThreadPool::SetThreadCount][2] workers=2
[Threading] Main thread CPU affinity mask set: 12
[f=-000001] [~ScopedOnceTimer][ISound::Init::New] 0ms
[f=-000001] [Sound] [ISound::Initialize] spawning sound-thread (0.0ms)
[f=-000001] [Sound] [Sound::UpdateThread][1] cfgMaxSounds=128
[f=-000001] [WatchDog::RegisterThread] registering controls for thread [audio]
[f=-000001] [Sound] [Sound::InitThread][1]
[f=-000001] [Sound] [Sound::InitThread][2] opening default device "OpenAL Soft"
[f=-000001] [Sound] [Sound::InitThread][3] device=06d39af0 context=05eaee70
[f=-000001] [Sound] [Sound::InitThread][4][OpenAL API Info]
[f=-000001] [Sound]   Vendor:         OpenAL Community
[f=-000001] [Sound]   Version:        1.1 ALSOFT 1.16.0
[f=-000001] [Sound]   Renderer:       OpenAL Soft
[f=-000001] [Sound]   AL Extensions:  AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
[f=-000001] [Sound]   ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFTX_HRTF ALC_SOFT_loopback ALC_SOFTX_midi_interface ALC_SOFT_pause_device
[f=-000001] [Sound]   Devices:
[f=-000001] [Sound]     [Speakers (Realtek High Definition Audio)]
[f=-000001] [Sound]     [Speakers (Realtek High Definition Audio)]
[f=-000001] [Sound]     [VX238-0 (NVIDIA High Definition Audio)]
[f=-000001] [Sound]     [VX238-4 (NVIDIA High Definition Audio)]
[f=-000001] [Sound] Error:   EFX: AL_INVALID_VALUE (40963)
[f=-000001] [Sound] Error:   Initializing EFX failed!
[f=-000001] [Sound] [Sound::UpdateThread][2]
[f=-000001] [~ScopedOnceTimer][ISound::Init::Dev] 100ms
[f=-000001] Joysticks found: 0
[f=-000001] [StartScript] Loading StartScript from: C:\Users\skymy\AppData\Roaming\springlobby\script.txt
[f=-000001] [CPreGame] client using IP 94.130.98.61 and port 8454
[f=-000001] [NetProto::InitClient] connecting to IP 94.130.98.61 on port 8454 using name [KING]skymyj
[f=-000001] [GR::LogDisplayMode] display-mode set to 1920x1080x24bpp@60Hz (fullscreen::decorated)
[f=-000001] [PreGame::AddGameSetupArchivesToVFS] using map: FolsomDamFlooded
[f=-000001] [PreGame::AddGameSetupArchivesToVFS] using game: Tech Annihilation test-8126-4184020 (archive: 789e6471d2879b4f0895a92fa3510071.sdp)
[f=-000001] [~CPoolArchive] name="C:\Users\skymy\Documents\My Games\Spring\packages\789e6471d2879b4f0895a92fa3510071.sdp" numZipFiles=10132 sumInflSize=225952kb sumReadTime=0ms
[f=-000001] 	file="anims/cursorattack_6.bmp" indx=8 inflSize=3kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_7.bmp" indx=9 inflSize=3kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_2.bmp" indx=4 inflSize=3kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_5.bmp" indx=7 inflSize=2kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_3.bmp" indx=5 inflSize=2kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_1.bmp" indx=3 inflSize=3kb readTime=0ms
[f=-000001] 	file=".gitignore" indx=1 inflSize=0kb readTime=0ms
[f=-000001] 	file=".gitattributes" indx=0 inflSize=0kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_0.bmp" indx=2 inflSize=3kb readTime=0ms
[f=-000001] 	file="anims/cursorattack_4.bmp" indx=6 inflSize=2kb readTime=0ms
[f=-000001] PreGame::GameDataReceived] recording demo to "C:\Users\skymy\Documents\My Games\Spring\demos\20180219_104615_FolsomDamFlooded_104.sdfz"
[f=-000001] [~ScopedOnceTimer][PreGame::GameDataReceived] 124ms
[f=-000001] [PreGame::UpdateClientNet] received user number 0 (team 0, allyteam 0), creating load-screen
[f=-000001] [LuaIntro] Searching for new Widgets
[f=-000001] [LuaIntro] Scanning: LuaIntro/Addons/
[f=-000001] [LuaIntro] Scanning: LuaIntro/Widgets/
[f=-000001] [LuaIntro] Scanning: LuaIntro/SystemAddons/
[f=-000001] [LuaIntro] Scanning: LuaIntro/SystemWidgets/
[f=-000001] [LuaIntro] Scanning: LuaIntro/chili/
[f=-000001] [LuaIntro] Found new widget "SpringLogo"
[f=-000001] [LuaIntro] Found new widget "LoadTexture"
[f=-000001] [LuaIntro] Found new widget "LoadProgress"
[f=-000001] [LuaIntro] Found new widget "Main"
[f=-000001] [LuaIntro] Found new widget "Music"
[f=-000001] [LuaIntro] Loading widgets   <>=vfs  **=raw  ()=unknown
[f=-000001] [LuaIntro] Loading widget:      Engine Taskbar Stuff   <engine_taskbar_control.lua>
[f=-000001] [LuaIntro] Loading widget:      LoadProgress           <loadprogress.lua>
[f=-000001] [LuaIntro] Loading widget:      Main                   <main.lua>
[f=-000001] [LuaIntro] Loading widget:      Music                  <music.lua>
[f=-000001] [LuaIntro] Loading widget:      LoadTexture            <bg_texture.lua>
[f=-000001] [LuaIntro] LuaIntro v1.0 (Lua 5.1)
[f=-000001] [LoadScreen::Init] single-threaded
[f=-000001] [WatchDog::RegisterThread] registering controls for thread [load]
[f=-000001] [Game::LoadGame][1] globalQuit=0 threaded=0
[f=-000001] Parsing Map Information
[f=-000001] Loading SMF
[f=-000001] Loading Map (77 MB)
[f=-000001] Loading Radar Icons
[f=-000001] Loading GameData Definitions
[f=-000001] [unitdefs.lua] Error: removed armecs unitDef, missing model file  (armecs)
[f=-000001] [unitdefs.lua] Error: removed tllecs unitDef, missing model file  (tllecs)
[f=-000001] [unitdefs.lua] Error: removed corecs unitDef, missing model file  (corecs)
[f=-000001] [unitdefs.lua] Error: removed the "tllecs" entry from the "tllesy" build menu
[f=-000001] [unitdefs.lua] Error: removed the "tllmmakerlvl3" entry from the "tllcom7" build menu
[f=-000001] [unitdefs.lua] Error: removed the "armecs" entry from the "armesy" build menu
[f=-000001] [defs.lua] Error: Failed to load armorDefs
[f=-000001] Error: 2, gamedata/defs.lua, [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 3, gamedata/armorDefs.lua, [string "gamedata/armorDefs.lua"]:17: '}' expected (to close '{' at line 3) near '"corshock"'

[f=-000001] [~ScopedOnceTimer][Game::LoadDefs (GameData)] 486ms
[f=-000001] Warning: [Game::LoadGame][1] forced quit with exception "Defs-Parser: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 3, gamedata/armorDefs.lua, [string "gamedata/armorDefs.lua"]:17: '}' expected (to close '{' at line 3) near '"corshock"'
"
[f=-000001] [Game::LoadGame][2] globalQuit=0 forcedQuit=1
[f=-000001] Creating Smooth Height Mesh
[f=-000001] [~ScopedOnceTimer][SmoothHeightMesh::MakeSmoothMesh] 28ms
[f=-000001] Creating QuadField & CEGs
[f=-000001] Warning: [Game::LoadGame][2] forced quit with exception "Error loading movement definitions"
[f=-000001] [Game::LoadGame][3] globalQuit=0 forcedQuit=1
[f=-000001] Loading Weapon Definitions
[f=-000001] [~ScopedOnceTimer][Game::PostLoadSim (WeaponDefs)] 0ms
[f=-000001] Warning: [Game::LoadGame][3] forced quit with exception "Error loading WeaponDefs"
[f=-000001] [Game::LoadGame][4] globalQuit=0 forcedQuit=1
[f=-000001] [~ScopedOnceTimer][Game::LoadInterface (Camera&Mouse)] 114ms
[f=-000001] [Sound] Error: [LoadSoundBuffer] unable to open audio file "MultiSelect"
[f=-000001] [Sound] Error: [Sound::GetSoundId] could not find sound "MultiSelect"
[f=-000001] Error: Spring 104.0 has crashed.
[f=-000001] Error: DLL information:
[f=-000001] Error: 0x00400000	spring
[f=-000001] Error: 0x77e10000	ntdll
[f=-000001] Error: 0x74e60000	KERNEL32
[f=-000001] Error: 0x6b220000	aswhookx
[f=-000001] Error: 0x760c0000	KERNELBASE
[f=-000001] Error: 0x76320000	ADVAPI32
[f=-000001] Error: 0x77b30000	msvcrt
[f=-000001] Error: 0x766f0000	sechost
[f=-000001] Error: 0x75bd0000	RPCRT4
[f=-000001] Error: 0x74830000	SspiCli
[f=-000001] Error: 0x74820000	CRYPTBASE
[f=-000001] Error: 0x75aa0000	bcryptPrimitives
[f=-000001] Error: 0x76480000	IMAGEHLP
[f=-000001] Error: 0x757a0000	ucrtbase
[f=-000001] Error: 0x767f0000	SHELL32
[f=-000001] Error: 0x75f10000	cfgmgr32
[f=-000001] Error: 0x74850000	shcore
[f=-000001] Error: 0x764a0000	combase
[f=-000001] Error: 0x750d0000	windows.storage
[f=-000001] Error: 0x75b20000	shlwapi
[f=-000001] Error: 0x758c0000	GDI32
[f=-000001] Error: 0x75db0000	gdi32full
[f=-000001] Error: 0x762a0000	msvcp_win
[f=-000001] Error: 0x758f0000	USER32
[f=-000001] Error: 0x75b00000	win32u
[f=-000001] Error: 0x75a90000	kernel.appcore
[f=-000001] Error: 0x77dc0000	powrprof
[f=-000001] Error: 0x75a70000	profapi
[f=-000001] Error: 0x76780000	WS2_32
[f=-000001] Error: 0x66be0000	GLU32
[f=-000001] Error: 0x60e50000	OPENGL32
[f=-000001] Error: 0x10000000	DevIL
[f=-000001] Error: 0x6b800000	OpenAL32
[f=-000001] Error: 0x77bf0000	ole32
[f=-000001] Error: 0x70780000	vorbisfile
[f=-000001] Error: 0x62e80000	zlib1
[f=-000001] Error: 0x70e40000	libfreetype-6
[f=-000001] Error: 0x65180000	libfontconfig-1
[f=-000001] Error: 0x62aa0000	glew32
[f=-000001] Error: 0x6c740000	SDL2
[f=-000001] Error: 0x76740000	IMM32
[f=-000001] Error: 0x75700000	OLEAUT32
[f=-000001] Error: 0x616a0000	MSVCP80
[f=-000001] Error: 0x66400000	MSVCR80
[f=-000001] Error: 0x714d0000	WINMM
[f=-000001] Error: 0x68140000	ogg
[f=-000001] Error: 0x64cc0000	vorbis
[f=-000001] Error: 0x68f40000	libexpat-1
[f=-000001] Error: 0x74130000	VERSION
[f=-000001] Error: 0x70580000	WINMMBASE
[f=-000001] Error: 0x67b90000	nvapi
[f=-000001] Error: 0x74a30000	SETUPAPI
[f=-000001] Error: 0x67af0000	dxgi
[f=-000001] Error: 0x70cf0000	uxtheme
[f=-000001] Error: 0x748e0000	MSCTF
[f=-000001] Error: 0x705d0000	dwmapi
[f=-000001] Error: 0x508e0000	nvoglv32
[f=-000001] Error: 0x735f0000	WTSAPI32
[f=-000001] Error: 0x70290000	DEVOBJ
[f=-000001] Error: 0x756a0000	WINTRUST
[f=-000001] Error: 0x750c0000	MSASN1
[f=-000001] Error: 0x74f30000	CRYPT32
[f=-000001] Error: 0x702c0000	ntmarta
[f=-000001] Error: 0x625e0000	nvspcap
[f=-000001] Error: 0x76770000	PSAPI
[f=-000001] Error: 0x74080000	WINHTTP
[f=-000001] Error: 0x75c90000	clbcatq
[f=-000001] Error: 0x671b0000	sxs
[f=-000001] Error: 0x72b80000	WINSTA
[f=-000001] Error: 0x5adf0000	TextInputFramework
[f=-000001] Error: 0x5abb0000	CoreUIComponents
[f=-000001] Error: 0x5ab20000	CoreMessaging
[f=-000001] Error: 0x665b0000	wintypes
[f=-000001] Error: 0x619e0000	d3d11
[f=-000001] Error: 0x67240000	shfolder
[f=-000001] Error: 0x63720000	nvldumd
[f=-000001] Error: 0x739f0000	CRYPTSP
[f=-000001] Error: 0x739c0000	rsaenh
[f=-000001] Error: 0x739a0000	bcrypt
[f=-000001] Error: 0x102c0000	nvwgf2um
[f=-000001] Error: 0x66550000	MMDevApi
[f=-000001] Error: 0x6c340000	PROPSYS
[f=-000001] Error: 0x60db0000	dsound
[f=-000001] Error: 0x66680000	AUDIOSES
[f=-000001] Error: 0x668a0000	AVRT
[f=-000001] Error: 0x60d70000	dinput8
[f=-000001] Error: 0x60c60000	inputhost
[f=-000001] Error: 0x6b150000	HID
[f=-000001] Error: 0x667d0000	XInput1_4
[f=-000001] Error: 0x6e830000	mswsock
[f=-000001] Error: 0x60c50000	wshqos
[f=-000001] Error: 0x60c40000	wshtcpip
[f=-000001] Error: 0x60c30000	wship6
[f=-000001] Error: 0x73b00000	dbghelp
[f=-000001] Error: Exception: Access violation (0xc0000005)
[f=-000001] Error: Exception Address: 0x00438e88
[f=-000001] Error: Stacktrace for Spring 104.0:
[f=-000001] Error: 	[ProgCtr=00438e88 StackPtr=0195f800 FramePtr=0195f8c8]
[f=-000001] Error: 	(0) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x00438E88]
[f=-000001] Error: 	(1) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x004396BE]
[f=-000001] Error: 	(2) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x004591B2]
[f=-000001] Error: 	(3) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x00459AF2]
[f=-000001] Error: 	(4) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x00460B09]
[f=-000001] Error: 	(5) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x004626D9]
[f=-000001] Error: 	(6) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x0088A53B]
[f=-000001] Error: 	(7) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x0086D1D3]
[f=-000001] Error: 	(8) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x00EC7B8B]
[f=-000001] Error: 	(9) C:\Users\skymy\Documents\My Games\Spring\engine\104.0\spring.exe [0x00401402]
[f=-000001] Error: 	(10) C:\WINDOWS\System32\KERNEL32.DLL [0x00018654]
[f=-000001] Error: 	(11) C:\WINDOWS\SYSTEM32\ntdll.dll [0x00064A77]
[f=-000001] Error: 	(12) C:\WINDOWS\SYSTEM32\ntdll.dll [0x00064A47]
[f=-000001] [WatchDog::DeregisterThread] deregistering controls for thread [main]
[f=-000001] Error: [ExitSpringProcess] errorMsg="Spring has crashed:
  Access violation.

A stacktrace has been written to:
  C:\Users\skymy\Documents\My Games\Spring\infolog.txt" msgCaption="Spring: Unhandled exception" mainThread=1
[f=-000001] [SpringApp::Kill][1] fromRun=0
[f=-000001] [ThreadPool::SetThreadCount][1] wanted=0 current=3 maximum=4 (init=0)
[f=-000001] 	[async=0] threads=3 tasks=80 {sum,avg}{exec,wait}time={{-0.000, -2.000}, {0.000, 0.000}}ms
[f=-000001] 		thread=1 tasks=40 {sum,min,max,avg}{exec,wait}time={{2.000, 0.000, 0.000, 2.000}, {0.000, 0.000, 0.000, 0.000}}ms
[f=-000001] 		thread=2 tasks=40 {sum,min,max,avg}{exec,wait}time={{-2.000, 0.000, 0.000, 26815622268077943021746420197982904111294613038947435329031835817127892636171287233871245824450136152631049712947223011355711144161236334327016575981322240.000}, {0.000, 0.000, -2.000, 0.000}}ms
[f=-000001] 	[async=1] threads=3 tasks=2 {sum,avg}{exec,wait}time={{0.000, 0.000}, {0.000, 0.000}}ms
[f=-000001] 		thread=1 tasks=1 {sum,min,max,avg}{exec,wait}time={{0.000, 0.000, 0.000, 0.000}, {0.000, 0.000, 0.000, 0.000}}ms
[f=-000001] 		thread=2 tasks=1 {sum,min,max,avg}{exec,wait}time={{0.000, 0.000, 0.000, 0.000}, {0.000, 0.000, 0.000, 0.000}}ms
[f=-000001] [ThreadPool::Set

**Comment by skymyj** [comment]
I check the corshock, but found no error

**Comment by nixtux** [comment]
Already fixed here https://github.com/techannihilation/TA/commit/0ca4f3693d2371e8f550d325b208925becbb40c7

**Comment by skymyj** [comment]
cool

**Comment by skymyj** [comment]
Ok for me. You can merge

**Comment by nixtux** [comment]
But what change did you make here?

**Comment by skymyj** [comment]
0 change.

**Comment by skymyj** [comment]
Just moved in good directory

**Comment by skymyj** [comment]
We need a new version

**Pull request merged**
