### PR TITLE
Proposition to fix armjeth Cob/3do

### PR DESCRIPTION
**Pull request by skymyj**
ATM, this unit is bugged. 
We have left gun synch with right smoke and flare... 
Bad animation to open arm (wrong direction)
No animation to close arm

With this PR : 
- Add good texture to show launcher
- all fixed (flare, gun, smoke)
- add animation to open/close arm
- add arm logo

image
image

Tested and work.

### CODE REVIEW

**Comment by nixtux** [comment]
fist in script NOW needs to be lower case
This also needs reverting https://github.com/techannihilation/TA/pull/1340/files#diff-1f3c023be3a9dc94c3903f85646add99R280 and this https://github.com/techannihilation/TA/pull/1340/files#diff-1f3c023be3a9dc94c3903f85646add99R282
as it wrong that so Static_Var_9 never goes below 20 why reset to 200

**Comment by skymyj** [comment]
Atm, the legs move correctly.
I only fixed weapon function and after compile COB, the logs move less faster.
In increase the static 9, the legs move like before. 
I don't understand why.

**Comment by skymyj** [comment]
On my computer, I have this message : (not always shown).
image

With the static9 at 200, nothing

**Comment by skymyj** [comment]
the CURRENT_SPEED get function don't work imo

**Comment by nixtux** [comment]
That function does work, it's used in so many script, must be an issue in your scriptor setup

**Comment by skymyj** [comment]
After the test with corsumo, i didn't change values to original settings
image
But after recompiling, always same thing

**Comment by nixtux** [comment]
Not that setup, was the script compiled in the ta/scripts directory or another game?

**Comment by skymyj** [comment]
Good :)

**Pull request merged**
