### PR TITLE
TLL EFUS Add for test

### PR DESCRIPTION
**Pull request by skymyj**
No added lupsfxs, cause the structure turning in Y axe.

### CODE REVIEW

**Comment by skymyj** [comment]
image

**Comment by nixtux** [comment]
Does the top part rotate around the central column, if so need to see fusion effect ingame.....

**Comment by nixtux** [comment]
Lol just read your comment about lups, did you try effect? Does it keep up?

**Comment by skymyj** [comment]
No I didn't have/test with Lups. Didn't know if Lups follower 3do model. I think not.
 And yes, the top part rotates.

**Comment by skymyj** [comment]
I know how fix the lups Fx. 
I will add an arm and the structure will not turn.
No need to have a arm turning to produce energy.

**Comment by skymyj** [comment]
I will repost soon a commit.

**Pull request merged**
