### PR TITLE
Balance_explosion_tech_center

### PR DESCRIPTION
**Pull request by skymyj**
Same effect than Nuclear Mines.
For all RC
We coud decrease more. But I don't know if Nix will accept

### CODE REVIEW

**Comment by skymyj** [comment]
#434

**Comment by ksilversurfer** [comment]
yes looks ok

**Comment by nixtux** [comment]
Don't change explosion!

**Comment by nixtux** [comment]
To muxh copy past from another explosion def

**Comment by ksilversurfer** [comment]
kk, but can we just nerf damage a bit?

**Comment by skymyj** [comment]
we can take the mine explosion for each Tech center.

Question : did we have wreckage for RC ?

**Comment by nixtux** [comment]
Visual effects has changed now :( revert it

**Pull request closed without merging**
