### PR TITLE
WIP Cloak bomber : Fix Model 

### PR DESCRIPTION
**Pull request by skymyj**
Wrong texture at many location (no synch between all textures).
Delete the turret. 
Fix missing piece.
https://1drv.ms/u/s!AgjKPxaKD1zLmU7RjXX1lB8VDMR6

### CODE REVIEW

**Comment by ksilversurfer** [comment]
this fix make no sens for me : P

**Comment by skymyj** [comment]
ATM Model : image

**Comment by skymyj** [comment]
sans titre

**Comment by skymyj** [comment]
Versus my mode lretextured and reworked : 
image

**Comment by nixtux** [comment]
Imo leave turret in and hide in create would be a better solution than purging part of the model

**Comment by skymyj** [comment]
with this merge, you have a nice model that fix all bugs.
There are no more turret, so model lost bytes and is less complexe with bos.
All work have be done. You prefer ignore all this work and just hide turret ? It will not hide all other imperfections 
image

**Comment by nixtux** [comment]
I'm saying the correct pr would have been fix textures and hide turret, not deleted it.

**Comment by skymyj** [comment]
Added the turret and hide them.

**Comment by skymyj** [comment]
After 2 hours, my conclusion is : the model can is bugged.
I remember, if you edit on 3dobuilder, you loose all modifications. 
So i can work only on upsring to change texture and try to fix Y possition wing.

I try many thing (import in wings and remake a new obj...) but all is bugged. 
So, 3 options : 
- didn't touch the atm model.
- use this request that work but no turrets.
- use a new model, like this : 
image

**Pull request closed without merging**
