### PR TITLE
Fix corsumo model / Cob bugs

### PR DESCRIPTION
**Pull request by skymyj**
image
#1299

### CODE REVIEW

**Comment by nixtux** [comment]
Please see https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/f959cf71c15cfb1b09ee4762b5ed9c552f5cfe03#diff-1f23d78e8778eab763e90fbc0e5ecdb2

**Comment by skymyj** [comment]
After testing : 
image

**Comment by nixtux** [comment]
Looks like that script values are set for a different linear constant, have you tried there script + model with touching it

**Comment by skymyj** [comment]
No. Only script

**Comment by nixtux** [comment]
We use a linear constant of 163840, I'm guessing that script is compiled with 65536

**Comment by skymyj** [comment]
Changed with BA values.

**Comment by nixtux** [comment]
As I said that script has an incorrect linear constant used v all our other units in its current state I wont merge it, instead I've updated the script in this commit https://github.com/techannihilation/TA/commit/d7b97d333b88c79ca9be440e7aee77e9b56ffdf9

**Pull request closed without merging**
