### PR TITLE
Update tllbarbarus.bos

### PR DESCRIPTION
**Pull request by skymyj**
Increase speed for AA Flak turret

### CODE REVIEW

**Comment by nixtux** [comment]
Why was this merged, Let's compare turnrates to arm static flak turret
https://github.com/techannihilation/TA/blob/master/scripts/armfflak.bos#L65
700 v 225  that's 3.1x less and
550 v 180 that's 3x less

**Comment by skymyj** [comment]
It's always better than 65. 
And in gameplay, it works. 
I can increase if you want. No prob.

**Comment by skymyj** [comment]
With reflexion. Instanetly speed = op.
I know in Ba.. it's the speed chosen.
But I played some space ship wargame anjd it's difficult for a stationnery AA weapon to shoot a fighter or someting else. In star wars, it's impossible that a destroyer kill a x-wing cause of the projectile speed and speed tower.
At 225 until 300 speed, the tower can easely kill targets and there is sense. instantanetly kill logic. And it can be a nerf for op flak in the game.

**Comment by nixtux** [comment]
So let's look at turn speed, how fast is it skymyj? j, let's see ;) so you have proposed a value of 225 degrees per second, all AA units need to be able todo a full 360 rotate before the next shot (yeah i know your weapons are locked to 190 degs on tllbarabus but if a target dies before it shoot it will need to re-aim so a fully 360 turn is needed), so your reload is 0.75s which means your weapon can only rotate 168.75 degs in between shot, as you can see it's not anywhere near the full  360 needed, now let's look at armflak 700 deg per second turn rate to the 0.52 reloadtime, which equals at 364 deg turn between shots, this is the reason why your request was closed your values have not been tested or thought about imo. So how did you come up with the values for barabus? Please explain as I can't work it out. Many thanks

**Comment by skymyj** [comment]
After some tests, i fixed armflak at 360 speed vs corflak at 700. 
After many waves testing, arm and core kill same numbers of planes (+/- 2%).
Anyways, it's ok for me 700. I'm talking about the t3 flak with instant turning at 1000 speed. Maybe reduce them at 700, cause there just are very strong.

**Comment by nixtux** [comment]
1000 degrees per seconds is not instant turn speed, only 'now' is. And using the same formula corpre with a reload of 0.2 should have a turn rate of 1800 degrees per second but it's already been reduced to nerfed to 1000.

**Pull request merged**
