### PR TITLE
Balance HP for TSAR

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Cost has already been incresead by 20% on last release

**Comment by nixtux** [comment]
Imo a x10 hp buff is too much, this unit need an achilles heal

**Comment by skymyj** [comment]
If you compare to Rapid Plasma T4, Same HP butcost x 4

**Comment by skymyj** [comment]
I'm ok for Achilles heal. Ok for 55K HP ?

**Comment by nixtux** [comment]
Yeah around the x3 mark is fine by me

**Pull request merged**
