### PR TITLE
Update buildmenu for builderlvl3 lvl4

### PR DESCRIPTION
**Pull request by skymyj**
Balance timebuild.
Add/Delete some units for better balance or add forgotten units.
Delete Tech3 for CrusH.

### CODE REVIEW

**Comment by ksilversurfer** [comment]
i need look at this pr closer

**Comment by skymyj** [comment]
Did you look ?

**Comment by skymyj** [comment]
In future, the t3 hover will be deleted from RC cons. (cause, there will be a new branch t3 hover).
We can find for a new t3.5 arm unit.

**Comment by ksilversurfer** [comment]
ok we can merge this, vote yes

**Pull request merged**
