### PR TITLE
Add supersonic scout

### PR DESCRIPTION
**Pull request by skymyj**
image

### CODE REVIEW

**Comment by ksilversurfer** [comment]
Reason we need this unit? - please make description!!! :)

**Comment by skymyj** [comment]
Reason : Same than all TX unit. 
Goal is to remplace 300 scout plane T1 by 50 T3. 
Less particules and better units.

**Comment by ksilversurfer** [comment]
hmmmmmmmmmmmm

**Comment by ksilversurfer** [comment]
idea is not bad tho

**Pull request merged**
