### PR TITLE
Change Names

### PR DESCRIPTION
**Pull request by Antarac**
Change "Long Range" in front of names into "Advanced",
like with "Advanced Protector", so there are not same
words in Name and Description.

"Hedgehog - Mobile Anti-Nuke System"	 Core T2 Vehicle
"Turtle - Mobile Anti-Nuke System" TLL T2 Kbot
"Scarab - Mobile Anti-Nuke System" Arm T2 Kbot

"Long Range Turtle - Mobile Long Range Anti-Nuke System" TLL T2.5 Kbot
"Long Range Scarab - Mobile Long Range Anti-Nuke System" Arm T2.5 Kbot

"Fortitude - Anti-Nuke System" Core T2 Building
"Peacemaker - Anti-Nuke System" TLL T2 Building
"Protector - Anti-Nuke System" Arm T2 Building

"Long Range Fortitude - Long Range Anti-Nuke System" Core T2.5 Building
"Long Range Peacemaker - Long Range Anti-Nuke System" TLL T2.5 Building
"Advanced Protector - Long Range Anti-Nuke System"	Arm T2.5 Building

"Hive - Aircraft Carrier with Anti-Nuke" Core T2 Ship
"Giant - Aircraft Carrier with Anti-Nuke" TLL T2 Ship
"Colossus - Aircraft Carrier with Anti-Nuke" Arm T2 Ship

"T3 Defensor - T3 Anti-Nuke System" Core T3 Building
"T3 Gazelle - T3 Anti-Nuke System" TLL T3 Building
"T3 Protector - T3 Anti-Nuke System" Arm T3 Building

### CODE REVIEW

**Comment by Antarac** [comment]
Change name of "Protector" into "Advocat" and all
T3 Anti-Nukes got their own unique Name so you can
delete "T3" in front of name to avoid double text.

**Comment by Antarac** [comment]
Name "Gazelle" doesn't fit for a
big Anti-Nuke System so rename
it with "Watchdog"?

**Comment by Antarac** [comment]
Rename "Defensor" to "Solicitor", since there is
no such word like "Defensor" as far as i know?

**Comment by nixtux** [comment]
https://en.m.wikipedia.org/wiki/53T6

**Comment by Antarac** [comment]
Allright, deleted the gazelle request.

**Pull request merged**
