### PR TITLE
Balance tllroaster.lua

### PR DESCRIPTION
**Pull request by skymyj**
#717 
Fix Main weapon Angle Turret
Add Good Ration E/M

### CODE REVIEW

**Comment by nixtux** [comment]
270 deg fire arc would be better imo

**Comment by skymyj** [comment]
armmanni have 180°.
what about 270+180 / 2 = 225° ?

**Comment by skymyj** [comment]
Players complain about the OP 360 turret. (Keiji)

**Comment by skymyj** [comment]
Done

**Pull request merged**
