### PR TITLE
Balance Pop-up damage vs commanders

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by Antarac** [comment]
Why is there extra damage to Commanders for some units?
For the Player its impossible to know which units do that,
or did i miss something?

**Comment by skymyj** [comment]
Yes. Player was blind except programmers :p
But nix implemented a damage widvet on lasr release. Space button after select an unit to see all damage class

**Comment by ksilversurfer** [comment]
extra damage to experimental??
extra damage to coms?
sorry but i dont understand....
**Pop-up should deal same damage too all ground units**

**Comment by ksilversurfer** [comment]
someday llt will deal 1500dmg to bantha and 10dmg to commanders XD
sorry but I dont understand idea of that...

**Comment by skymyj** [comment]
Deleted extra damage for commanders

**Comment by ksilversurfer** [comment]
vote yes

**Pull request merged**
