### PR TITLE
Balance Adv MM

### PR DESCRIPTION
**Pull request by skymyj**
ATM, they are so OP. 

Comparaison : 
5 core adv mm = 1280 capacity for 16.6 M/S
1 T2 MM = 1024 capacity for 14.3 M/S
Cost * 2 for T2 (1.3KM and 57KE) vs 940M and 30KE

We have to reduce capacity and increase a little Metal cost.

### CODE REVIEW

**Comment by skymyj** [comment]
We need add a tll adv too

**Comment by ksilversurfer** [comment]
i totally dont understand your calculations:
5 core adv mm = 1280 capacity for 16.6 M/S (is that t1.5??)
t2 metal maker has A3 class
t1.5 metal maker has AC2 class

**Comment by skymyj** [comment]
Yes indeed. You are right. T2 have better ratio. But it's same than adv fusion vs driller. Cause of the technology, they will be better.
But T1.5 ar really to Op.

Now if we decrease T1.5, we should decrease too the t1 at 1.0 / 100 and driller at 0.9 for example

**Comment by skymyj** [comment]
Is it possible to merge it ?

**Comment by ksilversurfer** [comment]
we need Keijj0 here to comment

**Pull request merged**
