### PR TITLE
Harmonise All Nano

### PR DESCRIPTION
**Pull request by skymyj**
ATM, between morph or make a T4 nano, there are differences. 
Between faction, there are changes too. T3 TLL OP (cause, before no T4 Nano TLL).
Delete energy use too.
Harmonise :
- builderpower (T1 T2 T3 T4): 250, 500, 1000, 2000
- Buildrange : 400, 600, 800, 1000

### CODE REVIEW

**Comment by skymyj** [comment]
Not finished. 
Naval nano and morph files to change.

**Comment by skymyj** [comment]
Work done.

**Comment by ksilversurfer** [comment]
wait wait, so morphing nanos wont cost anything? only time?

**Comment by ksilversurfer** [comment]
or if cost is removed from morph then it is calculated from cost difference?

**Comment by ksilversurfer** [comment]
I see nanos like this:

 ARM
- longest build distance, 
- lowest build power, 
- highest e cost, 
- lowest m cost,

CORE
- medium build distance, 
- medium build power, (or little on +)
- medium e cost, 
- medium m cost, (or little on  +)

TLL
- lowest build distance, 
- highest build power,
- lowest e cost, 
- highest m cost,

**Comment by skymyj** [comment]
Its difference cost like all other units.

**Comment by skymyj** [comment]
Do you prefer 2400 builpower and 900 range or 1600 buildpower and 1200 range.
Many players dont know the difference. I m for equalize all stats for this unit.

**Comment by nixtux** [comment]
BS closing PR

**Pull request closed without merging**
