### PR TITLE
balance armkrmi.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
reason? for me this unit is well balanced now

**Comment by skymyj** [comment]
I round up damage/s (333=>375).
Less range 400 => 380
Metal cost should increase a little

**Comment by ksilversurfer** [comment]
ok now

**Comment by ksilversurfer** [comment]
damege now not too low? : 
damage = {
:  -					default = 400,
:  +					default = 280,
  			
I would set 340

**Comment by skymyj** [comment]
per second = 333 vs 375 (reload has been decreased)

**Comment by ksilversurfer** [comment]
pls upate damage to mean value of 400 and 280 = 340

**Comment by ksilversurfer** [comment]
100% agree here 
vote Y

**Pull request merged**
