### PR TITLE
Add shield veh

### PR DESCRIPTION
**Pull request by skymyj**
image

### CODE REVIEW

**Comment by ksilversurfer** [comment]
ugly for me

**Comment by skymyj** [comment]
Well. need to merge even if the unit has not visual appropriated. 
We need this unit for Arm. We could change model later.
2 years i proposed like 5 - 6 models. 
If you have suggestion, i could add a model for this job.

**Comment by ksilversurfer** [comment]
i dislike the look of it

**Comment by skymyj** [comment]
it rocks ! 
image

**Comment by ksilversurfer** [comment]
idk, for me still ugly as hell, we need other ask ppl to vote :D

**Comment by skymyj** [comment]
image

**Comment by ksilversurfer** [comment]
this one looks better

**Comment by skymyj** [comment]
Done

**Pull request merged**
