### PR TITLE
Balance Shield Bot.lua

### PR DESCRIPTION
**Pull request by skymyj**
With T4 arrival, we need to balance the monkeylord. 

Goal is to have better HP and damage /s. 
Delete Shield and give All Terrain Hexapod.

### CODE REVIEW

**Comment by skymyj** [comment]
For Armpraet, goal is to decrese HP and increase Speed. 
Job : Rapid T3.5 Kbot for escort the exoarm

**Comment by Antarac** [comment]
All Terrain would be good for Monkeylord cause of
the big model it got problems with terrain often.

But for remove shields i vote no
cause i see no reason to remove it.

**Comment by skymyj** [comment]
Nix had added new caterories for unit.
Now there are t4 allterrain and shield. The monkey has both. Mayb to op.

**Comment by nixtux** [comment]
I think the shield should stay,  its iconic for that unit

**Comment by skymyj** [comment]
So my question is : is it possible to add shield for fatshrew (2 shields on side or 1 bigger shield ) ?

**Comment by skymyj** [comment]
Maybe we couls delete the allterrain feature for monkeylord and fatshrew

**Comment by nixtux** [comment]
3 shields is pointless and expensive in particles and particles cost performance.

**Comment by skymyj** [comment]
So just 1 bigger shield between T2 and T3 ?

**Comment by skymyj** [comment]
I just readded shield for monkeylord. And decrease HP.
I balance irritator. From last versions, irritator cost more for stats cause no lab cost. (was commander). So, these stats have been increased with a little increase resources cost.

**Comment by skymyj** [comment]
Changed canon plasma by lighting canon with restriction with angle.

**Comment by nixtux** [comment]
As I've said before don't change irritators weapon

**Comment by skymyj** [comment]
Done

**Comment by nixtux** [comment]
Why change the sound huts?, also weapon name for irritators cannon is now wrong

**Pull request merged**
