### PR TITLE
Fix crawling bombs Transport abuse

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
**It's a must**

**Comment by skymyj** [comment]
don't forget the second crawling bomb for core. (invisible)

**Comment by ksilversurfer** [comment]
checked that skymyj in game, it can't be transported

**Comment by nixtux** [comment]
What about stopping thoses units from exploding while in transport?

**Comment by ksilversurfer** [comment]
also good idea for me

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/902f8c2597f4b4c0b59efad964e743f48d44e588

**Pull request closed without merging**
