### PR TITLE
Increase Cost of RC from T2.5 to T4

### PR DESCRIPTION
**Pull request by ksilversurfer**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
if you dont like it pls say :P

**Comment by skymyj** [comment]
So, if I understand the logic here : 
- All the T2.5 and T3.5 units will be less played.
- All players will rush more Eco to have T3 Cons to have the good resources to get T2 and T3 battle units.

**Comment by ksilversurfer** [comment]
hmmm ok to leave t2.5 as it?

**Comment by ksilversurfer** [comment]
and maybe we need increase cost of t3 cons

**Pull request closed without merging**
