### PR TITLE
Rebalance juno + reduce glow effect, match size

### PR DESCRIPTION
**Pull request by sqrtone**
Juno need 2 hits to kill heavy mine.
Increased range +1000elmos
Reduced reload time 75 - > 45 sec

### CODE REVIEW

**Comment by skymyj** [comment]
Heavy Mine and Emp Mine with T2 resist to Juno. It's ok for me. 
Need 2 shots to destroy them. 
Atm, only (95%) medium and light mines are built.

**Comment by skymyj** [comment]
Did you test on heavy mines ? 
I set at 25dmg, cause, there is a lost of damage. I'm not sure, you kill easy heavy mines with 2 shots

**Comment by skymyj** [comment]
Or maybe, we could set all mines with 0 regen HP at all

**Comment by sqrtone** [comment]
yeah better 0 regen for mines

**Pull request merged**
