### PR TITLE
Add Saurus

### PR DESCRIPTION
**Pull request by skymyj**
After test it, you could add it in tllprototype

### CODE REVIEW

**Comment by nixtux** [comment]
Add what, without checking out your repo we have no idea what this is.

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA/pull/1356

**Comment by nixtux** [comment]
What's the particle cost when firing?

**Comment by nixtux** [comment]
To find out particle cost, enable globallos   /globallos  then alt + b to show debug windows, particle count is in the bottom left, report back max value when unit is firing.

**Comment by skymyj** [comment]
Default : 320
Missile : 700
Laser beam : 2000
Both : 10000

**Comment by nixtux** [comment]
Thoses values are different from silvers test, are you sure the missile fire was in Los or globallos was on?

**Comment by nixtux** [comment]
Default max count is 20000 with your test that unit used half of that which is way too expensive

**Comment by nixtux** [comment]
Can you please provide screenshot of weapon firing and debug view enabled and globallos, so we can compair values?

**Comment by nixtux** [comment]
Try again and before type /maxparticles 20000

**Comment by skymyj** [comment]
with /maxparticles 20000
image
image
image
image
image
image

**Pull request merged**
