### PR TITLE
Update krogtaar.lua

### PR DESCRIPTION
**Pull request by skymyj**
Proposition to balance Krogtaar.

### CODE REVIEW

**Comment by skymyj** [comment]
Bantha = 1.45 (for comparaison)

**Comment by ksilversurfer** [comment]
agree vote yes

**Comment by nixtux** [comment]
In future can we have need entry's in version.txt for all pull requests

**Comment by nixtux** [comment]
Vote y btw

**Comment by skymyj** [comment]
Sure. I will

**Pull request merged**
