### PR TITLE
Add CRAWL_BLASTSML explosion to T2.5

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
#362

**Comment by Antarac** [comment]
Does this make the explosions bigger or smaller than before?

**Comment by skymyj** [comment]
Smaller. You have all info here : https://github.com/techannihilation/TA/tree/master/weapons

	crawl_blast = {
		areaofeffect = 400,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.4,
		explosiongenerator = "custom:FLASHNUKE360",
		impulseboost = 0.123,
		impulsefactor = 0.123,
		name = "CrawlingBomb",
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 1250,
			crawlingbombs = 200,
			default = 2500,
		},
},

	crawl_blastsml = {
		areaofeffect = 250,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.3,
		explosiongenerator = "custom:FLASHNUKE280",
		impulseboost = 0,
		impulsefactor = 0,
		name = "WimpyCrawlingBomb",
		range = 400,
		reloadtime = 3,
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 1000,
			crawlingbombs = 100,
			default = 2000,
		},
},

**Comment by Antarac** [comment]
Thanks! Sounds good to make it smaller.

**Comment by Antarac** [comment]
Can we close this if it's merged?

**Pull request merged**
