### PR TITLE
Balance ColdFusion

### PR DESCRIPTION
**Pull request by skymyj**
With increase cost of metal maker, need a buff.

### CODE REVIEW

**Comment by skymyj** [comment]
The coldfusion didnt have balance with increase metal cost from T2 Builder.

**Comment by ksilversurfer** [comment]
its ok i think, btw. some ppl blame that tll has weak eco.
You should take a look on that.

**Comment by skymyj** [comment]
Yes I know. But you can calcul, its good balance between 1adv fus tll + adv metalal maker vs 1 adv core/arm and 3 adv mm.

**Comment by skymyj** [comment]
More time and manage  to build them but more resourses too for arm/core

**Pull request merged**
