### PR TITLE
Update missile truck

### PR DESCRIPTION
**Pull request by skymyj**
#1226

### CODE REVIEW

**Comment by skymyj** [comment]
V0 : 
Less agility move and speed.
Damage increased at 20/s
Cost : increase metal and decrease energy (ratio is more balanced now. They cost too much E before.

V1 : 
Less agility move and speed.
Delete burst : no sense to have 2 missile / shot from 1 barrel. It will decrease particules too.
Cost : Decrease energy cost (they cost too much before).

**Comment by nixtux** [comment]
From silver 'little bit more HP should be fine.', your pr contains way too many other authorized changes, please make new pr with only wanted changes

**Comment by skymyj** [comment]
Not from silver but antarac

**Comment by skymyj** [comment]
Atm tll is better than arm core. 
So need balance arm core into tll or tll into arm/core.

**Comment by nixtux** [comment]
https://github.com/CommanderSpice/Phoenix-Annihilation/blob/master/units/cormist.lua#L6
https://github.com/CommanderSpice/Phoenix-Annihilation/blob/master/units/armsam.lua#L6
Need I say anymore

**Comment by skymyj** [comment]
In Phoenix Annihilation, these units are used 90% for AA. So all comparaison with TA are useless in term of balance.
Now, we can increase cost difference between faction.

**Comment by nixtux** [comment]
What you talked about in https://github.com/techannihilation/TA/issues/1226 was a couple of unit stats changed not to a total rebalance.......

**Comment by ksilversurfer** [comment]
i vote to remove tracks = true from tll missile trucks, make them simillar to core / arm,
if you want tll to be different you can make them stealthy maybe - no idea if will be op or not,
but Guided projectile is OP so i vote to make them tracks = false,

**Comment by nixtux** [comment]
@sikver currently they all have that set 
https://github.com/techannihilation/TA/blob/master/units/cormist.lua#L161
https://github.com/techannihilation/TA/blob/master/units/armsam.lua#L164
https://github.com/techannihilation/TA/blob/master/units/tllannouncer.lua#L147

What tllannouncer does have if faster turnrate by just over 100, the big one.......... 10x brake rate increase and 5x acceleration rate v arm/core counterparts 
IMO that needs to be fixed way before anything else happens

**Comment by skymyj** [comment]
If you reopen, i fixed the tll values.

**Comment by nixtux** [comment]
Not going to reopen, I will push changes to make tll inline with arm/core counterpart

**Comment by Antarac** [comment]
My comment "little bit more HP should be fine" was a comment, not a decision or command.
Also it was only about hp not about 15 changes like here.
Why making pull request if nothing was decided in the issue?
Why use my issue comment for pull request with different changes?

I could add another 10 reasons why it piss me off to use my comment and bend it till it fits!

**Comment by skymyj** [comment]
The fact is : I will never use again these fucking missile shit.
I try to play them from many game play. 
If you can't trust high ts player and a developper. I don't care too.

**Pull request closed without merging**
