### PR TITLE
Balance Extractor Storage

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by ksilversurfer** [comment]
vote yes

**Comment by nixtux** [comment]
Revert tll mex output changes

**Comment by skymyj** [comment]
I understand. I begin to change storage. 
But I'm thinking about new T1.5 TLL MEx.
Before, T1 was better than Arm/Core, cause no T1.5. 
T2 was less, cause T2 was cheaper.

No I think, we should have same value for all now

**Comment by nixtux** [comment]
tll was inital balance with old mex output, changing now would upset balance imo, that where there so expensive in M

**Comment by nixtux** [comment]
No every units/faction needs the same stats, variety is the spice of life.

**Comment by skymyj** [comment]
Revert extract Done
Except for adv underwater (was lower then ground )

**Comment by skymyj** [comment]
So i change to fix with the ground

**Pull request closed without merging**
