### PR TITLE
Add EMP To armhorg.lua

### PR DESCRIPTION
**Pull request by skymyj**
#115

### CODE REVIEW

**Comment by skymyj** [comment]
Less burst to decrease CPU calculs => special for Nix :)

**Comment by nixtux** [comment]
Emp unit explosion?

**Comment by skymyj** [comment]
Yes :) Arm are the EMP specialist. 
This unit will find a job for skirmish

**Comment by nixtux** [comment]
I was on about this units death explosions, now it has an emp weapon on death it should explode like one

**Comment by nixtux** [comment]
Needs emp type unit explosion on death/self-d

**Comment by skymyj** [comment]
Add TWILIGHT. 
Maybe too much ? 
(same than extractor ARM T1 )

**Comment by nixtux** [comment]
> This branch has conflicts that must be resolved

**Pull request closed without merging**
