### PR TITLE
Gunships damage each other, part 2

### PR DESCRIPTION
**Pull request by Antarac**
Gunships damage each other #202

The rest of the Gunships
and Choppers that miss:
avoidfriendly = false,
collidefriendly = false,

### CODE REVIEW

**Comment by Antarac** [comment]
Nixtux, you mentioned once to remove it from laser gunships.

If you still want i can remove it from "armjade" and "corcrw"
and add the changes to this pull request.

**Comment by nixtux** [comment]
Yeah please do

**Comment by Antarac** [comment]
Removed it from "armjade" and "corcrw".

All old units from arm and core contained
"avoidfriendly = false," and "collidefriendly = false,".

Units that didn't contain it were mostly the
tll units and choppers that got created later.

Any other units like heros or torpedo
gunships you wanna add as well?

**Comment by Antarac** [comment]
The "collidefriendly = false," is added to Capital Ships now.

**Pull request merged**
