### PR TITLE
Add MDS for TLL and all Air engineers

### PR DESCRIPTION
**Pull request by skymyj**
Same than Arm/Core Engineer

### CODE REVIEW

**Comment by skymyj** [comment]
Add T1 Construction.
Add amphibot for ArchNano (like other engineer)

**Comment by skymyj** [comment]
Delete T2 cons from engineer.. Lile Arm/Core.
Add T1 Cons like Arm / Core

**Comment by ksilversurfer** [comment]
Agree

**Comment by skymyj** [comment]
Can you merge this ?
(I don't want conflicts with MDS commits)

**Comment by skymyj** [comment]
Need merge please

**Comment by skymyj** [comment]
Work done. 
I added MDS.

**Comment by ksilversurfer** [comment]
we should add to ground engineers too ! :)
Adding only to air will confuse players

**Comment by skymyj** [comment]
Already added for ground

**Comment by ksilversurfer** [comment]
yes i just not noticed :D

**Pull request merged**
