### PR TITLE
Add armshieldgen

### PR DESCRIPTION
**Pull request by skymyj**
I'm happy to share and present my first creation with 3do, script file, lua files.

The shield vehicule is good answer to corshieldgen.

All tested and work. Nix, can you test in local. Maybe could have issue i didn't see cause of my inexperience.

Thanks

### CODE REVIEW

**Comment by skymyj** [comment]
Update Bos/COs File. 
Adding the NOHEATCLOUD to killed function.

**Comment by nixtux** [comment]
Hardly looks like a shield gen unit

**Comment by skymyj** [comment]
Added sphere for arm shield. 
But, sphere doesn't active. (I changed bos/cob too).
Do you know, if I missed something ? 
capture

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/issues/294

**Comment by skymyj** [comment]
I know I'm not a good example to follow rules but I respect some :) 
#416

**Comment by nixtux** [comment]
It's ugly, not getting added.

**Comment by skymyj** [comment]
The picture in top is not the object 3DO ATM. ATM unit looks like to : https://1drv.ms/i/s!AgjKPxaKD1zLlGIgeEX7aum-Jfkh
You said it doesn't look like to a shield unit. So i copied pasted the sphere from corshieldgen. But :
> But, sphere doesn't active. (I changed bos/cob too).
> Do you know, if something missed ?

**Comment by skymyj** [comment]
With the good widget / SFX, it gives that : 
capture

**Comment by nixtux** [comment]
It's not the missing sfx it needs, the units itself does not look like its emitting some sort of shield, it's not bulky enough, missing something to hold shield sphere etc.

**Comment by skymyj** [comment]
I understand. I fixed the object that hold shield sphere
capture

**Comment by skymyj** [comment]
[ARMSHIELDGEN.zip](https://github.com/techannihilation/TA/files/1569122/ARMSHIELDGEN.zip)

**Comment by skymyj** [comment]
New Design with Kbot : 
capture
Equiped with Emp laser.

**Pull request closed without merging**
