### PR TITLE
Add second weapon for Armmcv

### PR DESCRIPTION
**Pull request by skymyj**
#739

### CODE REVIEW

**Comment by skymyj** [comment]
Tested & work

**Comment by nixtux** [comment]
I dislike the removal of missiles

**Comment by skymyj** [comment]
I readded missile.

**Comment by nixtux** [comment]
No you didn't, atm missile won't fire, script need adjusting for this + unitdef

**Comment by skymyj** [comment]
I thought you spoke about lua unitdef file. 
So, I will add the missile script. 
But this unit needs rebalance if you add starburst.

**Comment by skymyj** [comment]
Added starburst and work and tested

**Comment by nixtux** [comment]
Why change targetable?

**Pull request merged**
