### PR TITLE
Add 3 Lua Files + update Morph

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
If you are agree with names, I will work balance for this 3 new commanders

**Comment by nixtux** [comment]
Yeah name is fine, you just need to balance and fix names in the unitdefs

**Comment by nixtux** [comment]
Line 2 on every file needs updating to new name

**Comment by skymyj** [comment]
Changes and balance done

**Comment by Antarac** [comment]
If the Commander is called Fusion Commander it
sounds like he should have a high energy output
himself.

**Comment by ksilversurfer** [comment]
agree with Antarac,  Fusion Commander should produce like 1500e

**Pull request merged**
