### PR TITLE
Balance adv crawling Bomb

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by Antarac** [comment]
Hard to understand why you wanna change this if you write nothing about it mate =)

**Comment by skymyj** [comment]
You are right. Sorry.

The cor adv crawling has too much hp and too op with invisible feature. 3.2k=>1.85 for 400m and 1.3 speed.
Other change is for turtoise : increase hp at 3.5k for 750m and 1.0speed

**Comment by nixtux** [comment]
Sorry but that only 2 units talked about but with changes for 5 units ?

**Comment by skymyj** [comment]
Indeed. Other changes concern timebuild. A little decrease for all crawling bomb. 
Vader, tll and core bomb are balanced in function of their cost. 
The vader was too weak vs corroach (cost speed and hp)
For tll, increase hp at +200 cause 450 metal for 1 unit. Less speed than vader or roach

**Comment by skymyj** [comment]
I think we could decrease again timebuild like mines. The crawling bomb are good alternative if you destroy adv def. So they need less timebuild to have better reactivity

**Comment by skymyj** [comment]
Just decrease a little. Not put 200 to timebuild :)

**Comment by ksilversurfer** [comment]
LOL nerf by 50% adv t2 crawling bombs...?
-		maxdamage = 3200,
 +		maxdamage = 1850,

srsly - i never use those becouse price is high,
my idea was to make tem oven more stronger, but your idea was to nerf...
pls stay at default maybe..

**Comment by skymyj** [comment]
I increased HP 1 year ago and it was a bad idea. On BA, Hp < 1000.

**Pull request merged**
