### PR TITLE
Balance T3 artillery ship vs other ship (and fix some bugs)

### PR DESCRIPTION
**Pull request by skymyj**
Fixed bug like angle turret.
Ratio M/E TLL.
Spice of life : TLL less damage but more AOE.
For Arty ship : Decrease damage from secondary weapon. (same power than bats weapon).
Add good flare in 3do model.

### CODE REVIEW

**Comment by skymyj** [comment]
image

**Comment by skymyj** [comment]
image
Turret is cor theme. Will change with tllcaps turret

**Comment by skymyj** [comment]
image

**Comment by ksilversurfer** [comment]
its not valid repisitory : "	skymyj wants to merge 10 commits into techannihilation:master from **unknown repository**"

**Pull request closed without merging**
