### PR TITLE
Update tlllasbot.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by pcdummy** [comment]
That improves tllasbot which is the TLL ak, right?

**Comment by ksilversurfer** [comment]
vote b

**Comment by skymyj** [comment]
So, this change to increase strenght of the green laser TLL. (better range (same as warrior) and better HP 100 vs 1300 for warrior. His speedis his principal strenght).
Cause, they have no t1.5 kbot. I d like have a kbot with same power than Arm Warrior.
(Like vehicle, they have a medium and a riot tank stronger than Arm / Core)

**Comment by pcdummy** [comment]
So with this change TLL T1 Kbot will be stronger than ARM/CORE T1 but weaker than T1.5 ARM/CORE?

**Comment by skymyj** [comment]
Yeap. And  weaker than warrior but 33% faster

**Comment by skymyj** [comment]
Need Vote ! yes or Not ? To you to choose !

**Comment by ksilversurfer** [comment]
vote y, i made tests :)

**Pull request merged**
